Fix 1.6 compatibility with CMA <1.4.7
The Checkmk 1.6 version can now be installed on Checkmk Appliance
firmwares older than 1.4.7.

Change-Id: Icff6fe0a270e5badc3946e5bd7a4f9b1e2e8328b

diff --git a/omd/packages/cma/post-install b/omd/packages/cma/post-install
--- a/omd/packages/cma/post-install
+++ b/omd/packages/cma/post-install
@@ -7,9 +7,9 @@ CAP_PROGRAMS="bin/mkeventd_open514 lib/nagios/plugins/check_icmp lib/nagios/plug
 
 for PROGRAM in $CAP_PROGRAMS; do
   PROGRAM_PATH=$PROGRAM
-  if [ -f $PROGRAM_PATH ]; then
-    chgrp omd $PROGRAM_PATH
-    chmod 750 $PROGRAM_PATH
+  if [ -f "$PROGRAM_PATH" ]; then
+    chgrp omd "$PROGRAM_PATH"
+    chmod 750 "$PROGRAM_PATH"
 
     if [ "$PROGRAM" = "lib/nagios/plugins/check_icmp" ]; then
         CAP="cap_net_raw+ep"
@@ -23,6 +23,11 @@ for PROGRAM in $CAP_PROGRAMS; do
         CAP="cap_net_bind_service+ep"
     fi
 
-    setcap $CAP $PROGRAM_PATH
+    # Capabilities are support as of CMA 1.4.7. To be compatible with older
+    # appliances, we add the setuid workaround here
+    if ! setcap "$CAP" "$PROGRAM_PATH"; then
+        echo "Failed to set capabilities $CAP for $PROGRAM. Falling back to setuid."
+        chmod 4750 "$PROGRAM"
+    fi
   fi
 done
