Re-enable parallel build for Googletest
This should reduce chroot setup time at least a bit. The output of
single build steps will be separated from each other, so the build
output should remain readable even if run in parallel - in the rare
case someone would still like to read it.

diff --git a/agents/windows/test/build-googletest b/agents/windows/test/build-googletest
--- a/agents/windows/test/build-googletest
+++ b/agents/windows/test/build-googletest
@@ -23,9 +23,17 @@ for project in test mock ; do
     # we only need the libs...
     targets=lib/libg${project}.la
     autoreconf --install
+    # Build 32 and 64 bit in parallel, wait for child processes to terminate.
+    children=()
     for arch in 32 64 ; do
-        build $arch
+        build $arch &
+        children+=($!)
     done
+    for pid in "${children[@]}" ; do
+        # If any subprocess fails, wait for the rest to exit in a controlled way.
+        wait $pid || { wait; exit 1; }
+    done
+
     # make install is not supported by Google -> copy headers and libs
     cp -r include/g${project} /usr/share/mingw-w64/include/
     for arch in 32 64 ; do
