shfmt init script
Change-Id: I6b7bda9f90243760b4595ff168a97614205c0ed4

diff --git a/omd/packages/stunnel/skel/etc/init.d/stunnel b/omd/packages/stunnel/skel/etc/init.d/stunnel
--- a/omd/packages/stunnel/skel/etc/init.d/stunnel
+++ b/omd/packages/stunnel/skel/etc/init.d/stunnel
@@ -14,7 +14,7 @@
 
 # Start only if LIVESTATUS_TCP with LIVESTATUS_TCP_TLS is enabled
 . ###ROOT###/etc/omd/site.conf
-if [ "$CONFIG_CORE" = none -o "$CONFIG_LIVESTATUS_TCP" = off -o "$CONFIG_LIVESTATUS_TCP" = off ] ; then
+if [ "$CONFIG_CORE" = none -o "$CONFIG_LIVESTATUS_TCP" = off -o "$CONFIG_LIVESTATUS_TCP" = off ]; then
     exit 5
 fi
 
@@ -24,61 +24,61 @@ CONFIG_FILE="###ROOT###/etc/stunnel/server.conf"
 PIDFILE="###ROOT###/tmp/run/stunnel-server.pid"
 
 case "$1" in
-    start)
-        echo -n 'Starting stunnel...'
-        if [ -e "$PIDFILE" ] ; then
-            PID=$(cat $PIDFILE)
-            if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
-                echo "Already running."
-                exit 0
-            fi
-            echo "removing stale pid file..."
-            rm -f $PIDFILE
+start)
+    echo -n 'Starting stunnel...'
+    if [ -e "$PIDFILE" ]; then
+        PID=$(cat $PIDFILE)
+        if [ -n "$PID" ] && ps $PID >/dev/null 2>&1; then
+            echo "Already running."
+            exit 0
         fi
+        echo "removing stale pid file..."
+        rm -f $PIDFILE
+    fi
 
-        $DAEMON $CONFIG_FILE && echo OK || echo Error
+    $DAEMON $CONFIG_FILE && echo OK || echo Error
     ;;
-    stop)
-        echo -n 'Stopping stunnel...'
-        PID=$(cat $PIDFILE 2>/dev/null)
-        if [ -z "$PID" ] ; then
-            echo "not running."
-        elif kill "$PID" ; then
-            echo -n 'waiting for termination..'
-            N=0
-            while [ -d /proc/$PID ] ; do
-                sleep 0.05
-                if [ $((N % 20)) -eq 0 ]; then
-                    echo -n .
-                fi
-                N=$((N+1))
-                if [ $N -ge 400 ] ; then
-                    echo "still running after 20 secs!"
-                    exit 1
-                fi
-            done
-            echo "OK"
-        else
-            echo "Failed"
-        fi
-    ;;
-    restart|reload)
-        $0 stop
-        $0 start
-    ;;
-    status)
-        echo -n 'Checking status of stunnel...'
-        if [ -e "$PIDFILE" ] ; then
-            PID=$(cat $PIDFILE)
-            if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
-                echo "running"
-                exit 0
+stop)
+    echo -n 'Stopping stunnel...'
+    PID=$(cat $PIDFILE 2>/dev/null)
+    if [ -z "$PID" ]; then
+        echo "not running."
+    elif kill "$PID"; then
+        echo -n 'waiting for termination..'
+        N=0
+        while [ -d /proc/$PID ]; do
+            sleep 0.05
+            if [ $((N % 20)) -eq 0 ]; then
+                echo -n .
             fi
-        fi
-        echo "stopped"
-        exit 1
+            N=$((N + 1))
+            if [ $N -ge 400 ]; then
+                echo "still running after 20 secs!"
+                exit 1
+            fi
+        done
+        echo "OK"
+    else
+        echo "Failed"
+    fi
     ;;
-    *)
-        echo "Usage: $0 {start|stop|restart|reload|status}"
+restart | reload)
+    $0 stop
+    $0 start
+    ;;
+status)
+    echo -n 'Checking status of stunnel...'
+    if [ -e "$PIDFILE" ]; then
+        PID=$(cat $PIDFILE)
+        if [ -n "$PID" ] && ps $PID >/dev/null 2>&1; then
+            echo "running"
+            exit 0
+        fi
+    fi
+    echo "stopped"
+    exit 1
+    ;;
+*)
+    echo "Usage: $0 {start|stop|restart|reload|status}"
     ;;
 esac
