mk-oracle: add manual regression test #1
mk-oracle is ready to be tested - just pre-install OCI with `./run --all`)
mk_oracle still to be refined

Change-Id: I424303fa2c8cf94f29e7b100ecc01344fcc976fb

diff --git a/packages/mk-oracle/cargo_run b/packages/mk-oracle/cargo_run
--- a/packages/mk-oracle/cargo_run
+++ b/packages/mk-oracle/cargo_run
@@ -14,11 +14,15 @@
 # limitations under the License.
 #
 # SPDX-License-Identifier: Apache-2.0
+failure() {
+    echo "ERROR: $1" >&2
+    exit 1
+}
+
 if [[ -z "${CI_ORA2_DB_TEST_PASSWORD}" ]]; then
     failure "CI_ORA2_DB_TEST_PASSWORD is not set in the environment, component testing will fail."
 fi
 export CI_ORA2_DB_TEST="ora-rocktest.dev.checkmk.net:system:$CI_ORA2_DB_TEST_PASSWORD:1521:FREE::FREE.cmkoratest:_:_:"
-echo "CI_ORA2_DB_TEST is constructed and exported"
 path_to_runtime="${PWD}/runtimes/plugins/packages/mk-oracle"
 export LD_LIBRARY_PATH="${path_to_runtime}:${LD_LIBRARY_PATH}"
 export MK_CONFDIR="${PWD}"
