Add missing exit code for sles15*
Change-Id: I58bb9109a3f38ddacfe885e6fe19e8832d074cd7

diff --git a/omd/distro b/omd/distro
--- a/omd/distro
+++ b/omd/distro
@@ -123,6 +123,8 @@ fi
 if [ -e /etc/os-release ]; then
     . /etc/os-release
     echo "${NAME}${SEP}${VERSION/-/}"
+    exit 0
 fi
 
+echo >&2 "ERROR: Cannot determine Linux distribution!"
 exit 1
