Files must not be installed to etc, tmp, var
The files in /omd/version/[version]/{etc,tmp,var} will
not be usable by sites. The packages need to put their
files for these directories to /omd/version/[version]/skel/{etc,tmp,var}
instead. This commit fixes some wrong installed directories
and adds validations after build.

Change-Id: Id3c4c6d222c2d5843e6cf1fa3a1d3cd105632236

diff --git a/omd/Makefile b/omd/Makefile
--- a/omd/Makefile
+++ b/omd/Makefile
@@ -230,6 +230,15 @@ $(INSTALL_GLOBAL): $(INSTALL)
 	if [ -f COMMIT ]; then \
 	    install -m 644 COMMIT $(DESTDIR)$(OMD_ROOT)/share/doc ; \
 	fi
+
+# Perform some validations
+	for SKEL_DIR in tmp var etc; do \
+	    if [ -d "$(DESTDIR)$(OMD_ROOT)/$$SKEL_DIR" ]; then \
+	        echo "ERROR: The directory $$SKEL_DIR is only allowed to exist in skel/" ; \
+	        find "$(DESTDIR)$(OMD_ROOT)/$$SKEL_DIR" ; \
+	        exit 1 ;
+	    fi ; \
+	done
 	$(TOUCH) $@
 
 omd.spec: omd.spec.in
