Unify cmk-graphing & cmk-werks a bit more.
Change-Id: I0f7e3281f3b6920b84f20fd0363295cce2de9856

diff --git a/packages/cmk-werks/run b/packages/cmk-werks/run
--- a/packages/cmk-werks/run
+++ b/packages/cmk-werks/run
@@ -1,38 +1,205 @@
 #!/bin/bash
-# Copyright (C) 2023 Checkmk GmbH - License: GNU General Public License v2
+# Copyright (C) 2022 Checkmk GmbH - License: GNU General Public License v2
 # This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 # conditions defined in the file COPYING, which is part of this source code package.
 
 set -e
 
-cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
+JOBS=6
 
-echo "run: install dependencies from Pipfile.lock"
-pipenv sync --dev
+failure() {
+    test ${#@} -eq 0 || echo "$(basename "$0"):" "$@" >&2
+    exit 1
+}
 
-echo "run: black"
-pipenv run black --check --diff werks tests
+usage() {
+    echo "usage: $(basename "$0") [OPTION]..."
+    echo "Run the CI pipeline or parts of it."
+    echo
+    echo "  -c, --clean             remove artifacts first"
+    echo "  -F, --check-format      check for correct formatting (isort, black)"
+    echo "  -u, --unit-tests        run unit tests"
+    echo "  -m, --mypy              run mypy"
+    echo "  -p, --pylint            run pylint"
+    echo "  -B, --bandit            run bandit"
+    echo "  -a, --all               shortcut for -F -u -m -p -B -C"
+    echo "  -f, --format            format sources"
+    echo "  -d, --documentation     generate documentation"
+    echo "  -j N, --jobs=N          allow N jobs at once, default is ${JOBS}"
+    echo "  -h, --help              show this help"
+}
 
-echo "run: isort"
-pipenv run isort --check --diff werks tests
+parse_options() {
+    # Yes, all those option variables are global.
+    RUN_CLEAN=no
+    RUN_CHECK_FORMAT=no
+    RUN_UNIT_TESTS=no
+    RUN_MYPY=no
+    RUN_PYLINT=no
+    RUN_BANDIT=no
+    RUN_FORMAT=no
+    RUN_DOCUMENTATION=no
 
-echo "run: tests"
-pipenv run pytest tests
+    if ! OPTIONS=$(getopt --options 'cFumpBafdj:h' --long 'clean,check-format,unit-tests,mypy,pylint,bandit,all,format,documentation,jobs:,help' --name "$(basename "$0")" -- "$@"); then
+        usage >&2
+        failure
+    fi
+    eval set -- "$OPTIONS"
+    unset OPTIONS
 
-echo "run: mypy"
-pipenv run mypy werks tests
+    while true; do
+        case "$1" in
+            '-c' | '--clean')
+                RUN_CLEAN=yes
+                shift
+                continue
+                ;;
+            '-F' | '--check-format')
+                RUN_CHECK_FORMAT=yes
+                shift
+                continue
+                ;;
+            '-u' | '--unit-tests')
+                RUN_UNIT_TESTS=yes
+                shift
+                continue
+                ;;
+            '-m' | '--mypy')
+                RUN_MYPY=yes
+                shift
+                continue
+                ;;
+            '-p' | '--pylint')
+                RUN_PYLINT=yes
+                shift
+                continue
+                ;;
+            '-B' | '--bandit')
+                RUN_BANDIT=yes
+                shift
+                continue
+                ;;
+            '-a' | '--all')
+                RUN_CHECK_FORMAT=yes
+                RUN_UNIT_TESTS=yes
+                RUN_MYPY=yes
+                RUN_PYLINT=yes
+                RUN_BANDIT=yes
+                shift
+                continue
+                ;;
+            '-f' | '--format')
+                RUN_FORMAT=yes
+                shift
+                continue
+                ;;
+            '-d' | '--documentation')
+                RUN_DOCUMENTATION=yes
+                shift
+                continue
+                ;;
+            '-j' | '--jobs')
+                JOBS="$2"
+                shift 2
+                continue
+                ;;
+            '-h' | '--help')
+                usage
+                exit 0
+                ;;
+            '--')
+                shift
+                test ${#@} -eq 0 || failure "extra arguments:" "$@"
+                break
+                ;;
+            *) failure "internal error" ;;
+        esac
+    done
 
-echo "run: pylint"
-pipenv run pylint werks tests
+    readonly RUN_CLEAN RUN_CHECK_FORMAT RUN_UNIT_TESTS RUN_MYPY RUN_PYLINT RUN_BANDIT RUN_FORMAT RUN_DOCUMENTATION JOBS
+}
 
-echo "run: bandit"
-pipenv run bandit --configfile=pyproject.toml --severity-level=high --recursive werks tests
+run_pipenv() {
+    PIPENV_CACHE_DIR="$(pwd)/.cache" \
+    PIPENV_VENV_IN_PROJECT=true \
+    PIPENV_NOSPIN=true \
+    PIPENV_HIDE_EMOJIS=true \
+    PIPENV_NO_INHERIT=true \
+    PIPENV_PIPFILE="$(pwd)/Pipfile" \
+    PIPENV_IGNORE_VIRTUALENVS=1 \
+        pipenv "$@"
+}
 
-echo "run: license-header"
-mapfile -t FILES <<<"$(find . -path "./run" -o -name '*.py' -type f -not -path "./build/*")"
-FOUND_PROBLEMS=$(grep -L '^# Copyright .C. 20.. Checkmk GmbH - License: GNU General Public License v2$' "${FILES[@]}") || true
-if [ -n "$FOUND_PROBLEMS" ]; then
-    echo -e "found no license headers in the following files:\n$FOUND_PROBLEMS"
-else
-    echo "  all files seem ok"
-fi
+setup_venv() {
+    test "${SETUP_VENV_RAN}" = "yes" && return
+    # --quiet doesn't really work, see https://github.com/pypa/pipenv/issues/5037, but redirecting
+    # stdout is OK, errors go to stderr, and so do the initial venv creation messages.
+    run_pipenv sync --dev >/dev/null
+    run_pipenv clean
+    # poor man's "activate", but without any danger of naming clashes
+    PATH="$(pwd)/.venv/bin:$PATH"
+    hash -r
+    SETUP_VENV_RAN=yes
+}
+
+run_clean() {
+    rm -rf .cache .mypy_cache .pytest_cache .venv ./*.egg-info build
+    find werks tests -type d -name __pycache__ -print0 | xargs --null --no-run-if-empty rm -rf
+}
+
+run_check_format() {
+    setup_venv
+    isort --check-only --diff werks tests
+    black --check --diff werks tests
+}
+
+run_unit_tests() {
+    setup_venv
+    pytest
+}
+
+run_mypy() {
+    setup_venv
+    mypy
+}
+
+run_pylint() {
+    setup_venv
+    PYTHONPATH=. pylint --jobs="${JOBS}" werks tests
+}
+
+run_bandit() {
+    setup_venv
+    # We would like to put everything into pyproject.toml, so running just "bandit" would do the
+    # right thing. But bandit is totally obscure & complicated regarding configuration, see several
+    # issues like https://github.com/PyCQA/bandit/issues/606.  :-/
+    bandit --configfile=pyproject.toml --quiet --recursive --severity-level=high werks tests
+}
+
+run_format() {
+    setup_venv
+    isort werks tests
+    black werks tests
+}
+
+run_documentation() {
+    echo "TODO: generate documentation"
+}
+
+main() {
+    # Change to the directory where this script resides, it makes many things easier
+    # and we can call this script from everywhere.
+    cd -- "${BASH_SOURCE%/*}"
+    parse_options "$@"
+    test ${RUN_CLEAN} = yes && run_clean
+    test ${RUN_CHECK_FORMAT} = yes && run_check_format
+    test ${RUN_UNIT_TESTS} = yes && run_unit_tests
+    test ${RUN_MYPY} = yes && run_mypy
+    test ${RUN_PYLINT} = yes && run_pylint
+    test ${RUN_BANDIT} = yes && run_bandit
+    test ${RUN_DOCUMENTATION} = yes && run_documentation
+    test ${RUN_FORMAT} = yes && run_format
+    true
+}
+
+main "$@"
