7774 FIX Fix installation issue on older debian based distros
The werk #7344 introduced compatibility issues with Linux setups that don't
support linux capabilities (for different reasons). One reason may be a kernel
that does not support the capabilities.

We have added a fallback to the Checkmk debian packages that tries to use the
linux capabilities (as described in #7344). Once that fails it falls back to
setting the SETUID bit on the binaries, just like Checkmk did it before.

Change-Id: I4c563f067ec638531d769f0c36a170b7ae84d397

diff --git a/omd/debian/postinst.in b/omd/debian/postinst.in
--- a/omd/debian/postinst.in
+++ b/omd/debian/postinst.in
@@ -58,8 +58,8 @@ case "$1" in
 
     for PROGRAM in $CAP_PROGRAMS; do
       PROGRAM_PATH=$BASE_PATH/$PROGRAM
-      if [ -f $PROGRAM_PATH ]; then
-        setperm root omd 750 $PROGRAM_PATH
+      if [ -f "$PROGRAM_PATH" ]; then
+        setperm root omd 750 "$PROGRAM_PATH"
 
         if [ "$PROGRAM" = "lib/nagios/plugins/check_icmp" ]; then
             CAP="cap_net_raw+ep"
@@ -73,7 +73,15 @@ case "$1" in
 	    CAP="cap_net_bind_service+ep"
         fi
 
-	setcap $CAP $PROGRAM_PATH
+        # On some platforms the linux capabilities don't work as expected for different reasons.
+        # Some have too old kernels or kernels without capabilities supprt. There are propably
+        # other conditions, like filesystems without support for this. To keep Checkmk working
+        # as before on these systems and as secure as possible on newer systems we first try to
+        # set the capabilities and once that fails we fall back to setuid.
+        if ! setcap "$CAP" "$PROGRAM_PATH"; then
+            echo "Failed to set capabilities $CAP for $PROGRAM. Falling back to setuid."
+            chmod 4750 "$PROGRAM"
+        fi
       fi
     done
 
