Win-agent: Run unit tests only in its own target
Do not run unit tests as a post-build step. Produce XUnit XML output for
the unit tests.

diff --git a/agents/windows/build-agent b/agents/windows/build-agent
--- a/agents/windows/build-agent
+++ b/agents/windows/build-agent
@@ -25,7 +25,12 @@ windowsdir="/$CHROOT_BUILD_DIR/agents/windows"
 
     autoreconf --install
 
-    build_archs=(32 64)
+    for chk_target in unittest unittest-coverage-html integrationtest check ; do
+        if [[ " $targets " =~ " $chk_target " && "$targets" != "$chk_target" ]] ; then
+            echo "$chk_target cannot be combined with other targets"
+            exit 1
+        fi
+    done
 
     if [[ " $targets " =~ " integrationtest " && "$targets" != integrationtest ]] ; then
         echo "integrationtest cannot be combined with other targets"
@@ -37,18 +42,15 @@ windowsdir="/$CHROOT_BUILD_DIR/agents/windows"
         exit 1
     fi
 
-    if [[ "$targets" == unittest || "$targets" == integrationtest \
-              || "$targets" == unittest-coverage-html ]] ; then
-        # Only unittest, integrationtest or unittest-coverage-html
-        build_archs=()
-    elif [[ "$targets" == check ]] ; then
+    # Build test-related targets only in 64 bit
+    if [[ "$targets" =~ unittest || "$targets" == integrationtest \
+              || "$targets" == check ]] ; then
         build_archs=(64)
-    elif [[ " $targets " =~ " unittest " ]] ; then
-        # unittest together with other target(s)
-        targets=${targets/unittest/}
+    else
+        build_archs=(32 64)
     fi
 
-    # Build 32 and 64 bit in parallel, wait for child processes to terminate.
+    # Build archs in parallel, wait for child processes to terminate.
     children=()
     for arch in "${build_archs[@]}" ; do
         build $arch &
@@ -70,17 +72,5 @@ windowsdir="/$CHROOT_BUILD_DIR/agents/windows"
             mv check_mk_agent.msi ..
             cd -
         )
-    fi
-
-    if [[ ! "$targets" =~ clean && "$targets" != integrationtest ]] ; then
-        if [[ "$targets" != unittest-coverage-html ]] ; then
-            targets=unittest
-        fi
-        build 64
-    fi
-
-    if [[ " $targets " =~ " integrationtest " ]] ; then
-        targets=integrationtest
-        build 64
     fi
 )
