make-chroot: check for sudo environment
Change-Id: I33fba713b4cb3bae92ba4625191b1fa56a3060bc

diff --git a/agents/windows/make-chroot b/agents/windows/make-chroot
--- a/agents/windows/make-chroot
+++ b/agents/windows/make-chroot
@@ -17,6 +17,10 @@ if [ -z $CHROOT_PATH ]; then
     exit 1
 fi
 
+if [ -z $SUDO_USER ]; then
+    echo "ERROR: $0 must be executed with sudo"
+    exit 1
+fi
 
 cleanup_chroot() {
     PIDS=$(lsof -Fp $CHROOT_PATH 2>/dev/null | cut -dp -f2)
