17012 SEC Check for predefined connections when deploying in legacy mode
When a pre-defined connection is shipped, but on the system is no
systemd we don't install our cmk-agent-ctl but fall back to legacy mode.

That would open an unencrypted port which is unexpected.

CMK-12997

Change-Id: Ib96008eb83c3520a3197d3f5f2fc1e53b2977d37

diff --git a/agents/scripts/super-server/1_xinetd/setup b/agents/scripts/super-server/1_xinetd/setup
--- a/agents/scripts/super-server/1_xinetd/setup
+++ b/agents/scripts/super-server/1_xinetd/setup
@@ -7,6 +7,9 @@ MYSELF="$(realpath -- "$0" || printf "%s" "$0")"
 TEMPLATE="/etc/check_mk/xinetd-service-template.cfg"
 DESTINATION="/etc/xinetd.d"
 SERVICE_FILE="check-mk-agent"
+# In a CCE you can configure auto registration, that cannot be achieved with xinetd
+# if this file exists we assume that was configured. (See CMK-12997)
+PREDEFINED_CONNECTIONS_PATH="/var/lib/cmk-agent/pre_configured_connections.json"
 
 usage() {
     cat >&2 <<HERE
@@ -31,6 +34,16 @@ _xinetd_present() {
     return 1
 }
 
+_predefined_connection_not_present() {
+    if [ -e ${PREDEFINED_CONNECTIONS_PATH} ]; then
+        printf "A auto-registration rule was configured for this host!\n" >&2
+        printf "The agent controller does not support the xinetd setup and therefore transport encryption and auto-registration are not available!\n" >&2
+        printf "Since this might be expected we abort here. If xinetd should really be used exclude this host from the rule that configures the auto-registration\n" >&2
+        return 1
+    fi
+    return 0
+}
+
 _xinetd_running() {
     pgrep -G 0 -x xinetd >/dev/null 2>&1
 }
@@ -50,6 +63,8 @@ HERE
 deploy() {
 
     _xinetd_present || return 1
+
+    _predefined_connection_not_present || return 1
 
     mkdir -p "${DESTINATION}" || return 1
 
