Expand error message
CMK-17089

Change-Id: I7b5a361bc1291bfd46077e23dbbbb6b2e292e852
(cherry picked from commit e254a5470a6aed70b5e6cf732b014add1d3626d6)

diff --git a/omd/packages/omd/next_free_port b/omd/packages/omd/next_free_port
--- a/omd/packages/omd/next_free_port
+++ b/omd/packages/omd/next_free_port
@@ -25,7 +25,7 @@ port_is_used () {
             fi
         else
             if ! ls "${site_conf}" >/dev/null 2>&1; then
-                echo "ERROR: Failed to read config ${conf} of site ${S}. ${KEY} port will possibly be allocated twice" >&2
+                echo "ERROR: Failed to read config ${site_conf} of site ${S}. ${KEY} port will possibly be allocated twice" >&2
                 continue
             fi
 
