create TLS server certificate
Server certificate is created in etc/ssl/marcv
if it doesn't already exist.
marcv is run with the certificate.

Change-Id: Ifb6503fbe29dd5ebcf16c3aea836f1b352424147

diff --git a/omd/packages/check_mk/skel/etc/init.d/marcv b/omd/packages/check_mk/skel/etc/init.d/marcv
--- a/omd/packages/check_mk/skel/etc/init.d/marcv
+++ b/omd/packages/check_mk/skel/etc/init.d/marcv
@@ -3,6 +3,8 @@
 # This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
 # conditions defined in the file COPYING, which is part of this source code package.
 
+KEYFILE=$OMD_ROOT/etc/ssl/marcv/server_key.pem
+CERTFILE=$OMD_ROOT/etc/ssl/marcv/server_cert.pem
 PIDFILE=$OMD_ROOT/tmp/run/marcv.pid
 PID=$(cat $PIDFILE 2>/dev/null)
 
@@ -15,6 +17,12 @@ case "$1" in
             exit 0
         fi
 
+        create_server_certificate
+        if [ $? != 0 ]; then
+            echo "ERROR"
+            exit 1
+        fi
+
         if [ "$OMD_SITE" == "comp_remote" ]; then
             port=8001
         else
@@ -24,6 +32,8 @@ case "$1" in
         gunicorn -D -p $PIDFILE  \
                 --error-logfile $OMD_ROOT/var/log/marcv/error.log \
                 --access-logfile $OMD_ROOT/var/log/marcv/access.log \
+                --keyfile=$KEYFILE \
+                --certfile=$CERTFILE \
                 -b 127.0.0.1:$port \
                 -k uvicorn.workers.UvicornWorker marcv.server:app
         if [ $? -eq 0 ]; then
