Use our common hack: Detect the right C++ compiler.
Change-Id: I7a7ccb54cd16ae9008e16c435d8c6fec91395334

diff --git a/omd/packages/re2/Makefile b/omd/packages/re2/Makefile
--- a/omd/packages/re2/Makefile
+++ b/omd/packages/re2/Makefile
@@ -11,7 +11,20 @@ DIR      = $(NAME)-$(VERSION)
 
 build:
 	tar xzf $(DIR).tar.gz
-	$(MAKE) -C $(DIR) DESTDIR=$(abspath dest) prefix=$(OMD_ROOT) install
+# basically what part of AC_PROC_CXX does
+	@CXX="" ; \
+	for PROG in g++-7 clang++-5.0 g++-6 clang++-4.0 g++-5 clang++-3.9 clang++-3.8 clang++-3.7 clang++-3.6 clang++-3.5 g++-4.9 g++ clang++; do \
+	    echo -n "checking for $$PROG... "; SAVED_IFS=$$IFS; IFS=: ; \
+	    for DIR in $$PATH; do \
+	        IFS=$$SAVED_IFS ; \
+	        test -z "$$DIR" && DIR=. ; \
+	        ABS_PROG="$$DIR/$$PROG" ; \
+	        test -x "$$ABS_PROG" && { CXX="$$ABS_PROG"; echo "$$CXX"; break 2; } ; \
+	    done ; \
+	    echo "no"; IFS=$$SAVED_IFS ; \
+	done ; \
+	test -z "$$CXX" && { echo "error: no C++ compiler found" >&2 ; exit 1; } ; \
+	$(MAKE) -C $(DIR) CXX="$$CXX" DESTDIR=$(abspath dest) prefix=$(OMD_ROOT) install
 
 install:
 
