mypy checking cleanup
* Move mypy helper script to standard location: scripts/run-mypy
* Move make targets to test-py3/Makefile (is tested using Python 3 venv)
* Typesheds are now located in tests-py3/typeshed
* Cleanup old tests/static

In case you have integrated mypy into your editor using the previous
tests/static/run_mypy script, you will have to update your editor
config.

Change-Id: I5c17726888cc185241ccd41eccb54031c3384116

diff --git a/scripts/run-pipenv b/scripts/run-pipenv
--- a/scripts/run-pipenv
+++ b/scripts/run-pipenv
@@ -9,7 +9,7 @@ PYTHON_VERSION=$1
 shift
 
 if [ -z "$PYTHON_VERSION" ]; then
-    echo "ERROR: run-pipenv [2|3] PIPENV-ARGS..."
+    echo "ERROR: run-pipenv [2|3] PIPENV-ARGS..." >&2
     exit 1
 fi
 
@@ -21,7 +21,7 @@ elif [ "$PYTHON_VERSION" = "3" ]; then
 fi
 
 if [ ! -d "$REPO_PATH/virtual-envs/$PYTHON_VERSION" ]; then
-    echo "ERROR: Invalid python version $PYTHON_VERSION given."
+    echo "ERROR: Invalid python version $PYTHON_VERSION given." >&2
     exit 1
 fi
 
