Re-add more lightweight mypy binary detection
Change-Id: I43b0526e6072f0776d9aa1c9e84b1791213dbb3c

diff --git a/scripts/run-mypy b/scripts/run-mypy
--- a/scripts/run-mypy
+++ b/scripts/run-mypy
@@ -5,6 +5,16 @@ set -e
 
 REPO_PATH=$(dirname $(dirname $(realpath "$0")))
 
+# Detect whether or not mypy is available and print out an error that is in the
+# same format as mypy issues. This message is understood by e.g. vims ALE and
+# displays and error that mypy could not be executed.
+VENV_MYPY_PATH="$REPO_PATH/virtual-envs/3.7/.venv/bin/mypy"
+if [ ! -f "$VENV_MYPY_PATH" ]; then
+    for LAST_ARG; do :; done
+    echo "$LAST_ARG:1: error: Could not find $VENV_MYPY_PATH"
+    exit 1
+fi
+
 # NOTE: We should NOT run this in "$REPO_PATH", otherwise mypy will make paths
 # in messages relative, which will confuse e.g. Emacs' flycheck mode.
 MYPYPATH="$REPO_PATH:$REPO_PATH/livestatus/api/python:$REPO_PATH/omd/packages/omd:$REPO_PATH/tests-py3:$REPO_PATH/tests-py3/typeshed" \
