run-cxx-linter in docker
Change-Id: I2bb1fb6733b54f3fe5a4dbcc1494b8acfdb859d9

diff --git a/scripts/run-cxx-linter b/scripts/run-cxx-linter
--- a/scripts/run-cxx-linter
+++ b/scripts/run-cxx-linter
@@ -6,42 +6,57 @@
 set -e
 TARGET=$1
 PATCHSET_REVISION=$2
+REPO_DIR="$(dirname $(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd))"
+CONTAINER="artifacts.lan.tribe29.com:4000/ubuntu-20.04:master-latest"
 
-REPO_DIR="$(dirname $(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd))"
+function execute_test() {
+    # Prevpare Makefiles, otherwise "make compile_commands.json" will fail
+    make -C $REPO_DIR config.h
 
-# Prevpare Makefiles, otherwise "make compile_commands.json" will fail
-make -C $REPO_DIR config.h
+    # To really compute only the files which need checking, we better make sure
+    # that our project is up-to-date without any further changes first.
+    make -j8
 
-# To really compute *only* the files which need checking, we better make sure
-# that our project is up-to-date without any further changes first.
-make -j8
+    # Having an up-to-date project file before running a linter is a good idea, too
+    # (i.e. target "compile_commands.json").
+    make compile_commands.json
 
-# Having an up-to-date project file before running a linter is a good idea, too
-# (i.e. target "compile_commands.json").
-make compile_commands.json
+    # ATTENTION! Extremely cunning hack ahead! Find out which files have been
+    # changed in the current directory for the given commit. Transform those file
+    # names into --what-if=... options for make and do a dry run with them. This
+    # outputs the compilation commands needed, which we massage a bit with grep and
+    # sed to finally find out which C/C++ we need to check. Brilliant!  :-D  ;-)
+    FILES_TO_CHECK=$(make --dry-run \
+        $(git diff-tree --no-commit-id --name-only -r --relative "${PATCHSET_REVISION}" |
+            sed 's/\(.*\)/--what-if=\1/') \
+        all-am |
+        grep -e '-MD -MP -MF' |
+        sed 's/ &&\\$//' |
+        sed "s,.* || echo '\\./'\`,," |
+        sed 's/.-c -o .\.o //' |
+        sort)
 
-# ATTENTION! Extremely cunning hack ahead! Find out which files have been
-# changed in the current directory for the given commit. Transform those file
-# names into --what-if=... options for make and do a dry run with them. This
-# outputs the compilation commands needed, which we massage a bit with grep and
-# sed to finally find out which C/C++ we need to check. Brilliant!  :-D  ;-)
-FILES_TO_CHECK=$(make --dry-run \
-                      $(git diff-tree --no-commit-id --name-only -r --relative "${PATCHSET_REVISION}" | \
-                            sed 's/\(.*\)/--what-if=\1/') \
-                      all-am | \
-                     grep -e '-MD -MP -MF' | \
-                     sed 's/ &&\\$//' | \
-                     sed "s,.* || echo '\\./'\`,," | \
-                     sed 's/.*-c -o .*\.o //' | \
-                     sort)
+    if test -z "${FILES_TO_CHECK}"; then
+        echo "==================== nothing to do"
+        exit 0
+    fi
 
-if test -z "${FILES_TO_CHECK}"; then
-    echo "==================== nothing to do"
-    exit 0
+    echo "==================== files to check:"
+    echo "${FILES_TO_CHECK}"
+
+    echo "==================== ${TARGET}"
+    make ${TARGET} FILES_TO_CHECK="$(echo ${FILES_TO_CHECK})"
+}
+
+if [ -z ${RUN_HERE} ]; then
+    echo "Running in Docker Container $CONTAINER"
+    docker run -d -t \
+        -v ${REPO_DIR}:/${REPO_DIR} \
+        -e RUN_HERE="true" \
+        -w ${PWD} \
+        $CONTAINER \
+        ${REPO_DIR}/scripts/$(basename "$0") $TARGET $PATCHSET_REVISION
+else
+    pwd \
+    && execute_test $TARGET $PATCHSET_REVISION
 fi
-
-echo "==================== files to check:"
-echo "${FILES_TO_CHECK}"
-
-echo "==================== ${TARGET}"
-make ${TARGET} FILES_TO_CHECK="$(echo ${FILES_TO_CHECK})"
