omd: Livestatus TCP daemon is now fully managed by omd
The livestatus TCP daemon configuration is now fully managed by omd.
The configuration file `etc/mk-livestatus/xinetd.conf` has been removed
from the omd skeleton. The active configuration is now written to
`etc/xinetd.d/livestatusv1` and managed exclusively by omd.

As a result, `omd diff` no longer incorrectly reports changes to
`etc/mk-livestatus/xinetd.conf` on a fresh site.

Manual modifications to the livestatus TCP daemon configuration outside
of `omd config` are no longer possible. To cover previously manual
configuration options, `omd config` has been extended with two new
parameters:

- `LIVESTATUS_INSTANCES`: Maximum number of server instances that can be
  started by xinetd.
- `LIVESTATUS_PER_SOURCE`: Maximum number of simultaneous connections
  allowed from a single source IP.

Incompatible change: If a site has local modifications to
`etc/mk-livestatus/xinetd.conf`, an update warning is shown prompting
to migrate those changes to `omd config` manually before the old file
is replaced.

CMK-26713

Change-Id: I51f16b16ac1e6532b1088051bfeb7de675936b5b

diff --git a/omd/packages/omd/skel/etc/init.d/xinetd b/omd/packages/omd/skel/etc/init.d/xinetd
--- a/omd/packages/omd/skel/etc/init.d/xinetd
+++ b/omd/packages/omd/skel/etc/init.d/xinetd
@@ -2,7 +2,7 @@
 
 # Start only if at least one xinetd-based service is activated.
 
-test "$(ls -A ${OMD_ROOT}/etc/xinetd.d/)" || exit 5
+grep -qr '^service' "${OMD_ROOT}/etc/xinetd.d/" 2>/dev/null || exit 5
 
 PIDFILE=${OMD_ROOT}/tmp/run/xinetd.pid
 
@@ -18,16 +18,16 @@ OPTS="-pidfile ${OMD_ROOT}/tmp/run/xinetd.pid -filelog ${OMD_ROOT}/var/log/xinet
 
 case "$1" in
     start)
- 	echo -n 'Starting xinetd...'
-	if [ -e "$PIDFILE" ] ; then
-	    PID=$(cat $PIDFILE)
-	    if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
-		echo "still running with pid $PID! Aborting!"
-		exit 1
-	    fi
-	    echo "removing stale pid file..."
-	    rm -f $PIDFILE
-	fi
+        echo -n 'Starting xinetd...'
+        if [ -e "$PIDFILE" ]; then
+            PID=$(cat $PIDFILE)
+            if [ -n "$PID" ] && ps $PID >/dev/null 2>&1; then
+                echo "still running with pid $PID! Aborting!"
+                exit 1
+            fi
+            echo "removing stale pid file..."
+            rm -f $PIDFILE
+        fi
 
         # Do not use usual system daemon path. Some start script
         # (e.g. SLES) will think that the system xinetd is already
@@ -36,52 +36,51 @@ case "$1" in
         cp $DAEMON $OMD_ROOT/var/tmp/xinetd
         $OMD_ROOT/var/tmp/xinetd $OPTS
         echo OK
-    ;;
+        ;;
     stop)
-	echo -n 'Stopping xinetd...'
+        echo -n 'Stopping xinetd...'
         PID=$(cat $PIDFILE 2>/dev/null)
-        if [ -z "$PID" ] ; then
-	    echo "not running."
-        elif kill "$PID" ; then
-	    echo "OK"
+        if [ -z "$PID" ]; then
+            echo "not running."
+        elif kill "$PID"; then
+            echo "OK"
         else
-	    echo "Failed"
+            echo "Failed"
         fi
         rm -f $OMD_ROOT/var/tmp/xinetd
-    ;;
+        ;;
     restart)
-	$0 stop
-	$0 start
-    ;;
+        $0 stop
+        $0 start
+        ;;
     reload)
-	echo -n 'Reloading xinetd...'
-	if [ -e "$PIDFILE" ] ; then
-	    PID=$(cat $PIDFILE)
-	    if kill -HUP $PID
-	    then
-		echo OK
-	    else
-		echo ERROR
-		exit 1
-	    fi
-	else
-	    echo "not running"
-	    exit 1
+        echo -n 'Reloading xinetd...'
+        if [ -e "$PIDFILE" ]; then
+            PID=$(cat $PIDFILE)
+            if kill -HUP $PID; then
+                echo OK
+            else
+                echo ERROR
+                exit 1
+            fi
+        else
+            echo "not running"
+            exit 1
         fi
-    ;;
+        ;;
     status)
-	echo -n 'Checking status of xinetd...'
-	if [ -e "$PIDFILE" ] ; then
-	    PID=$(cat $PIDFILE)
-	    if [ -n "$PID" ] && ps $PID > /dev/null 2>&1 ; then
-		echo "running"
-		exit 0
-	    fi
-	fi
-	echo "stopped"
-	exit 1
-    ;;
+        echo -n 'Checking status of xinetd...'
+        if [ -e "$PIDFILE" ]; then
+            PID=$(cat $PIDFILE)
+            if [ -n "$PID" ] && ps $PID >/dev/null 2>&1; then
+                echo "running"
+                exit 0
+            fi
+        fi
+        echo "stopped"
+        exit 1
+        ;;
     *)
-	echo "Usage: $0 {start|stop|restart|reload|status}"
-    ;;
+        echo "Usage: $0 {start|stop|restart|reload|status}"
+        ;;
 esac
