mk-job: improve variable names
Change-Id: Idf39d6297b3208ff537e3969d70014526f2a2b68

diff --git a/agents/mk-job b/agents/mk-job
--- a/agents/mk-job
+++ b/agents/mk-job
@@ -7,7 +7,7 @@ export MK_VARDIR=/var/lib/check_mk_agent
 TMPDIR=${TMPDIR:-/tmp}
 
 help() {
-    echo "Usage: mk-job IDENT PROGRAM [ARGS...]"
+    echo "Usage: mk-job JOB_NAME PROGRAM [ARGS...]"
     echo ""
     echo "Execute PROGRAM as subprocess while measuring performance information"
     echo "about the running process and writing it to an output file. This file"
@@ -22,20 +22,20 @@ if [ $# -lt 2 ]; then
     exit 1
 fi
 
-MYSELF=$(whoami)
-OUTPUT_PATH="${MK_VARDIR}/job/${MYSELF}"
-IDENT="${1}"
-TMP_FILE="${TMPDIR}/${IDENT}.$$"
-RUNNING_FILE="${OUTPUT_PATH}/${IDENT}.$$running"
-COMPLETED_FILE="${OUTPUT_PATH}/${IDENT}"
+CURRENT_USER=$(whoami)
+JOB_DIR="${MK_VARDIR}/job/${CURRENT_USER}"
+JOB_NAME="${1}"
+TMP_FILE="${TMPDIR}/${JOB_NAME}.$$"
+RUNNING_FILE="${JOB_DIR}/${JOB_NAME}.$$running"
+COMPLETED_FILE="${JOB_DIR}/${JOB_NAME}"
 
 shift
 
-if [ ! -d "${OUTPUT_PATH}" ]; then
-    if [ "${MYSELF}" = root ]; then
-        mkdir -p "${OUTPUT_PATH}"
+if [ ! -d "${JOB_DIR}" ]; then
+    if [ "${CURRENT_USER}" = root ]; then
+        mkdir -p "${JOB_DIR}"
     else
-        echo "ERROR: Missing output directory ${OUTPUT_PATH} for non-root user '${MYSELF}'." >&2
+        echo "ERROR: Missing output directory ${JOB_DIR} for non-root user '${CURRENT_USER}'." >&2
         exit 1
     fi
 fi
