doc: formatting
Change-Id: Ia24e2ba3b8e8da345aa3effa665b328451aa2259

diff --git a/doc/treasures/check_curl b/doc/treasures/check_curl
--- a/doc/treasures/check_curl
+++ b/doc/treasures/check_curl
@@ -20,7 +20,6 @@
 # URL   http, https or ftp url
 # TEXT  optional text to be searched in result page
 
-
 CURL_CODES="1      Unsupported protocol. This build of curl has no support for this protocol.
 2      Failed to initialize.
 3      URL malformat. The syntax was not correct.
@@ -91,41 +90,37 @@ CURL_CODES="1      Unsupported protocol. This build of curl has no support for t
 82     Could not load CRL file,  missing  or  wrong  format  (added  in 7.19.0)
 83     Issuer check failed (added in 7.19.0)"
 
-curl_error ()
-{
-   echo "$CURL_CODES" | while read code text
-   do
-      if [ "$code" = $1 ] ; then echo "$text" ; return ; fi
-   done
+curl_error() {
+    echo "$CURL_CODES" | while read code text; do
+        if [ "$code" = $1 ]; then
+            echo "$text"
+            return
+        fi
+    done
 }
 
-
-
-if [ "$1" = -P ]
-then
-  PROXYPASS=$2
-  PROXYURL=$3
-  PROXYOPTIONS="--proxy-basic --proxy-user $PROXYPASS --proxy $PROXYURL"
-  shift
-  shift
-  shift
+if [ "$1" = -P ]; then
+    PROXYPASS=$2
+    PROXYURL=$3
+    PROXYOPTIONS="--proxy-basic --proxy-user $PROXYPASS --proxy $PROXYURL"
+    shift
+    shift
+    shift
 else
-  PROXYOPTIONS=
+    PROXYOPTIONS=
 fi
 
-if [ "$1" = -NTLM ]
-then
-  NTLM=" --ntlm --negotiate -u $2 "
-  shift
-  shift
+if [ "$1" = -NTLM ]; then
+    NTLM=" --ntlm --negotiate -u $2 "
+    shift
+    shift
 else
     NTLM=
 fi
 URL=$1
 PURL=$(echo $URL | awk -F "/" '{print $1"//"$3}')
 
-if [ -z "$URL" ]
-then
+if [ -z "$URL" ]; then
     echo "Usage: [-P PROXYUSER:PROXYPASS PROXYURL] [-NTLM NTLM_USER:NTLM_PASSWORD] URL [SEARCHTEXT]"
     exit 3
 fi
@@ -135,31 +130,30 @@ CONTENT=$2
 # CURL="curl -A """Mozilla/4.0 (compatible; MSIE 6.0;)""" --silent --fail --insecure $PROXYOPTIONS $URL"
 # CURL="curl -A Mozilla/4.0 (compatible; MSIE 6.0;) --silent --fail --insecure $PROXYOPTIONS $URL"
 # CURL="curl  --silent --fail --insecure $PROXYOPTIONS $URL"
-if [ "$CONTENT" ]
-then
+if [ "$CONTENT" ]; then
     # if $CURL 2>&1 | fgrep -q "$CONTENT"
-    if curl $NTLM -A "Mozilla/4.0 (compatible; MSIE 6.0;)" --silent --fail --insecure $PROXYOPTIONS $URL 2>&1 | fgrep -q "$CONTENT"
-    then
+    if curl $NTLM -A "Mozilla/4.0 (compatible; MSIE 6.0;)" --silent --fail --insecure $PROXYOPTIONS $URL 2>&1 | fgrep -q "$CONTENT"; then
         echo "OK - $PURL found '$CONTENT' in answer"
         exit 0
     else
         exitcode=${PIPESTATUS[0]}
-        if [ "$exitcode" != 0 ]
-        then
-           msg=$(curl_error $exitcode)
-           echo "CRIT - $PURL not retrieved, $msg"
-           exit 2
+        if [ "$exitcode" != 0 ]; then
+            msg=$(curl_error $exitcode)
+            echo "CRIT - $PURL not retrieved, $msg"
+            exit 2
         else
-           echo "CRIT - $PURL retrieved, but '$CONTENT' not found in page"
-           exit 2
+            echo "CRIT - $PURL retrieved, but '$CONTENT' not found in page"
+            exit 2
         fi
     fi
 else
     # OUTPUT=$($CURL >/dev/null 2>&1 | head -n 1 ; exit ${PIPESTATUS[0]})
-    OUTPUT=$(curl $NTLM -A "Mozilla/4.0 (compatible; MSIE 6.0;)" --silent --fail --insecure $PROXYOPTIONS $URL >/dev/null 2>&1 | head -n 1 ; exit ${PIPESTATUS[0]})
+    OUTPUT=$(
+        curl $NTLM -A "Mozilla/4.0 (compatible; MSIE 6.0;)" --silent --fail --insecure $PROXYOPTIONS $URL >/dev/null 2>&1 | head -n 1
+        exit ${PIPESTATUS[0]}
+    )
     exitcode=$?
-    if [ "$exitcode" = 0 ]
-    then
+    if [ "$exitcode" = 0 ]; then
         echo "OK - $PURL retrieved"
         exit 0
     else
@@ -168,4 +162,3 @@ else
         exit 2
     fi
 fi
-
diff --git a/doc/treasures/localchecks/check_mount_rw b/doc/treasures/localchecks/check_mount_rw
--- a/doc/treasures/localchecks/check_mount_rw
+++ b/doc/treasures/localchecks/check_mount_rw
@@ -7,101 +7,100 @@
 #Henry Huang (http://blog.unicsolution.com)
 #Most updated file: https://github.com/bbhenry/check_mk_local/edit/master/check_mount_rw
 
-PROGNAME=`basename $0`
-PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
+PROGNAME=$(basename $0)
+PROGPATH=$(echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,')
 REVISION="1.0"
-FQDNNAME=`hostname -f`
+FQDNNAME=$(hostname -f)
 TESTFILE="test-rw-$FQDNNAME"
 RAND=$RANDOM
 
 print_usage() {
-	echo "Usage: $PROGNAME"
+    echo "Usage: $PROGNAME"
 }
 
 print_help() {
-	print_revision $PROGNAME $REVISION
-	echo ""
-	print_usage
-	echo ""
-	echo "This plugin will write temporary file to all detected nfs and glusterfs directories and read them to verify the network mount points are working without fail"
-	echo ""
-	exit 0
+    print_revision $PROGNAME $REVISION
+    echo ""
+    print_usage
+    echo ""
+    echo "This plugin will write temporary file to all detected nfs and glusterfs directories and read them to verify the network mount points are working without fail"
+    echo ""
+    exit 0
 }
 
 check_mount_rw() {
-	MOUNTPOINTS=(`grep -E 'glusterfs|nfs' /proc/mounts | awk '{ gsub("fuse.glusterfs","glusterfs",$3); print $2":"toupper($3) }'`)
+    MOUNTPOINTS=($(grep -E 'glusterfs|nfs' /proc/mounts | awk '{ gsub("fuse.glusterfs","glusterfs",$3); print $2":"toupper($3) }'))
 
-	for a in "${MOUNTPOINTS[@]}"
-	do
-		DIRECTORY=`echo $a | cut -f1 -d:`
-		CONNECTIONTYPE=`echo $a | cut -f2 -d:`
+    for a in "${MOUNTPOINTS[@]}"; do
+        DIRECTORY=$(echo $a | cut -f1 -d:)
+        CONNECTIONTYPE=$(echo $a | cut -f2 -d:)
 
-		timeout 1s ls $DIRECTORY/$TESTFILE
-		RET_V=$?
-		if [[ $RET_V -eq 124 || $RET_V -eq 137 ]]; then
-			echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Accessing mount point $DIRECTORY timed out"
-			continue
-		elif [[ $RET_V -eq 0 ]]; then
-			echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Test file $DIRECTORY/$TESTFILE already exist"
-			rm -f $DIRECTORY/$TESTFILE
-			continue
-		fi
+        timeout 1s ls $DIRECTORY/$TESTFILE
+        RET_V=$?
+        if [[ $RET_V -eq 124 || $RET_V -eq 137 ]]; then
+            echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Accessing mount point $DIRECTORY timed out"
+            continue
+        elif [[ $RET_V -eq 0 ]]; then
+            echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Test file $DIRECTORY/$TESTFILE already exist"
+            rm -f $DIRECTORY/$TESTFILE
+            continue
+        fi
 
-		timeout 1s echo $RAND > $DIRECTORY/$TESTFILE
-		RET_W=$?
-		if [[ $RET_W -eq 124 || $RET_W -eq 137 ]]; then
-			echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Writing test file to $DIRECTORY/$TESTFILE timed out"
-			continue
-		elif [[ $RET_W -ne 0 ]]; then
-			echo "3 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Unknown write error $RET_W has occured while writing test file to $DIRECTORY"
-			continue
-		fi
+        timeout 1s echo $RAND >$DIRECTORY/$TESTFILE
+        RET_W=$?
+        if [[ $RET_W -eq 124 || $RET_W -eq 137 ]]; then
+            echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Writing test file to $DIRECTORY/$TESTFILE timed out"
+            continue
+        elif [[ $RET_W -ne 0 ]]; then
+            echo "3 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Unknown write error $RET_W has occured while writing test file to $DIRECTORY"
+            continue
+        fi
 
-		TESTREAD=`timeout 1s cat $DIRECTORY/$TESTFILE`
-		RET_R=$?
-		if [[ $RET_R -eq 124 || $RET_R -eq 137 ]]; then
-			echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Reading test from $DIRECTORY/$TESTFILE timed out"
-			continue
-		elif [[ $RET_R -ne 0 ]]; then
-			echo "3 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Unknown read error $RET_R has occured while reading test file from $DIRECTORY/$TESTFILE"
-			continue
-		fi
+        TESTREAD=$(timeout 1s cat $DIRECTORY/$TESTFILE)
+        RET_R=$?
+        if [[ $RET_R -eq 124 || $RET_R -eq 137 ]]; then
+            echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Reading test from $DIRECTORY/$TESTFILE timed out"
+            continue
+        elif [[ $RET_R -ne 0 ]]; then
+            echo "3 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Unknown read error $RET_R has occured while reading test file from $DIRECTORY/$TESTFILE"
+            continue
+        fi
 
-		if [[ $TESTREAD -eq $RAND ]]; then
-			timeout 1s rm -f $DIRECTORY/$TESTFILE
-			RET_RM=$?
-			if [[ $RET_RM -eq 124 || $RET_RM -eq 137 ]]; then
-				echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Removing the test file from $DIRECTORY/$TESTFILE timed out"
-				continue
-			elif [[ $RET_RM -ne 0 ]]; then
-				echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Failed to remove the test file from $DIRECTORY/$TESTFILE"
-				continue
-			else
-				echo "0 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Write and read test to the $DIRECTORY mount point was successful"
-				continue
-			fi
-		else
-			echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Content in the test file from $DIRECTORY/$TESTFILE does not match the source input"
-			continue
-		fi
-	done
+        if [[ $TESTREAD -eq $RAND ]]; then
+            timeout 1s rm -f $DIRECTORY/$TESTFILE
+            RET_RM=$?
+            if [[ $RET_RM -eq 124 || $RET_RM -eq 137 ]]; then
+                echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Removing the test file from $DIRECTORY/$TESTFILE timed out"
+                continue
+            elif [[ $RET_RM -ne 0 ]]; then
+                echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Failed to remove the test file from $DIRECTORY/$TESTFILE"
+                continue
+            else
+                echo "0 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Write and read test to the $DIRECTORY mount point was successful"
+                continue
+            fi
+        else
+            echo "2 Mount_${CONNECTIONTYPE}_RW_:$DIRECTORY - Content in the test file from $DIRECTORY/$TESTFILE does not match the source input"
+            continue
+        fi
+    done
 }
 
 while getopts "hv" opt; do
-	case "$opt" in
-		h)
-			print_help
-			exit 0
-			;;
-		v)
-			echo "$PROGNAME version: $REVISION"
-			exit 0
-			;;
-		\?)
-			print_help
-			exit 0
-			;;
-	esac
+    case "$opt" in
+        h)
+            print_help
+            exit 0
+            ;;
+        v)
+            echo "$PROGNAME version: $REVISION"
+            exit 0
+            ;;
+        \?)
+            print_help
+            exit 0
+            ;;
+    esac
 done
 
 check_mount_rw
