provide hints for changing permissions
Change-Id: I956b7e2f212a92db3128f3e9ed2c4a952246379a

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -2813,6 +2813,7 @@ EOM
         if $MK_ORA_DEBUG_CONNECT; then
             echo "    Logindetails:           ${MK_DB_CONNECT}" >&2
             echo -e "    Error Message:          ${output:0:100}"
+            exit 1
         else
             echo '<<<oracle_instance:sep(124)>>>'
             echo -e "$output"
@@ -2847,9 +2848,119 @@ do_async_checks() {
     echo "$MK_ASYNC_SECTIONS_QUERY" | mk_ora_sqlplus "do_async_checks"
 }
 
+do_suggest_group() {
+    local MODE=$1
+    local USER=$2
+    local FILE=$3
+    if id -Gn "$USER" | "${GREP}" '\boinstall\b' >/dev/null; then
+        echo "  We suggest to change the group to oinstall and give $MODE permission for the group:"
+        echo "  chgrp oinstall \"$FILE\""
+        local m="x"
+        if [ "$MODE" = "read" ]; then
+            m="r"
+        fi
+        echo "  chmod g+$m \"$FILE\""
+    fi
+}
+
+do_test_file_permission() {
+    local MODE=$1
+    local USER=$2
+    local FILE=$3
+
+    local m="-x"
+    if [ "$MODE" = "read" ]; then
+        m="-r"
+    fi
+
+    if su "${USER}" -c "test $m \"$FILE\""; then
+        echo "* user \"$USER\" can $MODE $FILE"
+        true
+    else
+        echo "* ERROR! user \"$USER\" can NOT $MODE $FILE"
+        echo "  $(ls -dl "$FILE")"
+        do_suggest_group "$MODE" "$USER" "$FILE"
+        echo
+        false
+    fi
+}
+
+do_test_permissions() {
+    local DEFAULT_SQLNET="LOG_DIRECTORY_CLIENT=/var/log/check_mk/oracle_clientDIAG_ADR_ENABLED=OFFSQLNET.WALLET_OVERRIDE=TRUEWALLET_LOCATION=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/etc/check_mk/oracle_wallet)))"
+
+    echo
+    echo "---checking permissions-------------------------------------------------"
+    echo "see https://checkmk.atlassian.net/wiki/spaces/KB/pages/70582273/Troubleshooting+mk+oracle+for+Windows+and+Linux"
+    echo
+
+    local SQLPLUS="${ORACLE_HOME}/bin/sqlplus"
+    echo "* sqlplus binary: ${SQLPLUS}"
+    local BINARY_OWNER
+    BINARY_OWNER="$(get_binary_owner "$SQLPLUS")"
+    echo "* sqlplus binary owner: ${BINARY_OWNER}"
+    if ! needs_user_switch_before_executing "$SQLPLUS"; then
+        echo "* change user: false"
+        echo "------------------------------------------------------------------------"
+        return
+    fi
+    echo "* change user: true"
+
+    echo "* \$TNS_ADMIN: ${TNS_ADMIN}"
+    local PATH_SQLNET="$TNS_ADMIN/sqlnet.ora"
+    local PATH_TNSNAMES="$TNS_ADMIN/tnsnames.ora"
+    if ! do_test_file_permission "read" "$BINARY_OWNER" "$PATH_SQLNET"; then
+        echo "  If you use the AGENT BAKERY you have to use the rule 'sqlnet.ora premission group' to make this change permanently, otherwise it will be overwritten by an agent update."
+    fi
+    if [ -f "$PATH_TNSNAMES" ]; then
+        do_test_file_permission "read" "$BINARY_OWNER" "$PATH_TNSNAMES"
+    fi
+    echo
+
+    local GENERIC_ERROR_MESSAGE="
+  Could not login. In case you are using a wallet to connect, there might be a permission error.
+  Make sure that the wallet folder can be read and executed by user \"$BINARY_OWNER\" and
+  the files inside the wallet can be read by the user.
+  Consult your ora files for hints where the wallet is located:
+  $PATH_SQLNET
+  $PATH_TNSNAMES
+"
+
+    # let's go all in and see if the connection works:
+    if error=$(echo "" | mk_ora_sqlplus "do_testmode" "no" 2>&1); then
+        echo "* test login works"
+    else
+        echo "* test-login does not work!"
+        if echo "$error" | ${GREP} "ORA-12578" >/dev/null; then
+            echo "  ORA-12578 suggests, that there is an error reading the wallet."
+            if [ "$(sed '/^#/d' </etc/check_mk/sqlnet.ora | tr -d '\n' | sed -e 's/\s\+//g')" == "$DEFAULT_SQLNET" ]; then
+                echo "  Detected sqlnet.ora as suggested in the documentation."
+                local WALLET_PATH="/etc/check_mk/oracle_wallet"
+                if [ ! -d "$WALLET_PATH" ]; then
+                    echo
+                    echo "* '$WALLET_PATH' does not exist or is not a directory!"
+                else
+                    echo
+                    do_test_file_permission "read" "$BINARY_OWNER" "$WALLET_PATH"
+                    do_test_file_permission "execute" "$BINARY_OWNER" "$WALLET_PATH"
+                    for f in "$WALLET_PATH"/{c,e}wallet.*; do
+                        do_test_file_permission "read" "$BINARY_OWNER" "$f"
+                    done
+                fi
+            else
+                echo "$GENERIC_ERROR_MESSAGE"
+            fi
+        else
+            echo "$GENERIC_ERROR_MESSAGE"
+        fi
+    fi
+    echo "------------------------------------------------------------------------"
+}
+
 do_testmode() {
     local sections=$1
     local asections=$2
+
+    do_test_permissions
 
     echo
     echo "---login----------------------------------------------------------------"
