mk_oracle: ALL sections are executed as synchronous sections if logging enabled; Remove 'flock'
Change-Id: Id7f2e8c7110990f2f674ca099443d033d9e76338

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -52,7 +52,7 @@ display_usage () {
     echo "  -d                      Enable full bash debugging"
     echo "  -t                      Just check the connection"
     echo "  -l, --log               Logs certain steps while execution"
-    echo "                          ('flock' needs to be installed)"
+    echo "                          Note: ALL sections are executed as synchronous sections"
     echo "  -s, --sections S1,S2,.. Only execute stated sections"
     echo "                          Note: asynchronous sections are execute"
     echo "                          as synchronous sections"
@@ -86,15 +86,8 @@ while test -n "$1"; do
             ;;
 
         -l|--log)
-            if type flock > /dev/null 2>&1; then
-                MK_ORA_LOGGING=true
-                export MK_ORA_LOGGING
-            else
-                echo "You cannot use the option '--log': flock needs to be installed."
-                echo "Please run mk_oracle without '--log'."
-                display_usage >&2
-                exit 2
-            fi
+            MK_ORA_LOGGING=true
+            export MK_ORA_LOGGING
             shift
             ;;
 
@@ -351,72 +344,67 @@ fi
 
 logging () {
     if $MK_ORA_LOGGING; then
-        (
-            flock 200
+        local log_file="$MK_VARDIR/log/mk_oracle.log"
+        local criticality=
+        local args=
+        local header=
+        local to_stderr=false
 
-            local log_file="$MK_VARDIR/log/mk_oracle.log"
-            local criticality=
-            local args=
-            local header=
-            local to_stderr=false
+        let i=0
+        while test -n "$1"; do
+            case "$1" in
+                -o)
+                    criticality="0" # OK, default
+                    shift
+                    ;;
 
-            let i=0
-            while test -n "$1"; do
-                case "$1" in
-                    -o)
-                        criticality="0" # OK, default
-                        shift
-                        ;;
+                -w)
+                    criticality="1" # WARNING
+                    shift
+                    ;;
 
-                    -w)
-                        criticality="1" # WARNING
-                        shift
-                        ;;
+                -c)
+                    criticality="2" # CRITICAL
+                    shift
+                    ;;
 
-                    -c)
-                        criticality="2" # CRITICAL
-                        shift
-                        ;;
+                -u)
+                    criticality="3" # UNKNOWN
+                    shift
+                    ;;
 
-                    -u)
-                        criticality="3" # UNKNOWN
-                        shift
-                        ;;
+                -e)
+                    to_stderr=true
+                    shift
+                    ;;
 
-                    -e)
-                        to_stderr=true
-                        shift
-                        ;;
+                *)
+                    args[$i]="$1"
+                    i=$((i+1))
+                    shift
+                    ;;
+            esac
+        done
 
-                    *)
-                        args[$i]="$1"
-                        i=$((i+1))
-                        shift
-                        ;;
-                esac
-            done
+        if [ -z "${criticality}" ]; then
+            criticality="0"
+        fi
 
-            if [ -z "${criticality}" ]; then
-                criticality="0"
+        header="$(perl -MPOSIX -le 'print strftime "%F %T", localtime $^T') [${criticality}] ${args[0]}"
+
+        if [ "${#args[@]}" -le 1 ]; then
+            echo "$header" >> "$log_file"
+            if [ $to_stderr = true ]; then
+                echo "$header" >&2
             fi
-
-            header="$(perl -MPOSIX -le 'print strftime "%F %T", localtime $^T') [${criticality}] ${args[0]}"
-
-            if [ "${#args[@]}" -le 1 ]; then
-                echo "$header" >> "$log_file"
+        else
+            for arg in "${args[@]:1}"; do
+                echo "${header} $arg" >> "$log_file"
                 if [ $to_stderr = true ]; then
-                    echo "$header" >&2
+                    echo "${header} $arg" >&2
                 fi
-            else
-                for arg in "${args[@]:1}"; do
-                    echo "${header} $arg" >> "$log_file"
-                    if [ $to_stderr = true ]; then
-                        echo "${header} $arg" >&2
-                    fi
-                done
-            fi
-
-        ) 200>|/tmp/mk_oracle.lock
+            done
+        fi
     fi
 }
 
@@ -1814,7 +1802,7 @@ sql_asm_diskgroup () {
 #     SQLS_SECTION_NAME=sec_name            (optional; if not stated, 'oracle_sql' is used)
 #     SQLS_SECTION_SEP=separator            (optional; only useful if SQLS_SECTION_NAME is stated;
 #                                            ASCII code, eg. '58' means ':')
-#     SQLS_SID=sid1,sid2,...                (comma separated)
+#     SQLS_SIDS=sid1,sid2,...               (comma separated)
 #     SQLS_DIR=/path/to/dir                 (no trailing '/')
 #     SQLS_SQL=name.sql                     ()
 #     SQLS_PARAMETERS=params                (parameters as string, double quotes are removed)
@@ -1825,7 +1813,7 @@ sql_asm_diskgroup () {
 #
 #   A section is a function which may contain some of above parameters, eg:
 #   my_sec () {
-#       SQLS_SID=sid1,sid2
+#       SQLS_SIDS=sid1,sid2
 #       SQLS_SQL=name.sql
 #   }
 #   and is configure in mk_oracle.cfg
@@ -1966,10 +1954,9 @@ do_custom_sqls () {
         if $MK_ORA_DEBUG_CONNECT; then
             do_testmode_custom_sql
         else
-            if [ -z "$max_cache_age" ]; then
+            if $MK_ORA_LOGGING || [ -z "$max_cache_age" ]; then
                 local output=
                 output=$(echo -e "$MK_CUSTOM_SQLS_SECTION_QUERY" | mk_ora_sqlplus "do_custom_sqls" "yes")
-                logging "[${MK_SID}] [${section}] [custom_sql]" "Custom SQLS query output: $output"
                 handle_custom_sql_errors "$output"
             else
                 run_cached "$max_cache_age" do_async_custom_sqls "_custom_sql_${MK_CUSTOM_SQLS_SECTION}"
@@ -2172,6 +2159,7 @@ ora_session_environment () {
 #   '----------------------------------------------------------------------'
 
 run_cached () {
+    logging "[${MK_SID}] [run_cached]" "Note: Asynchronous sections are not executed during logging"
     if [ -n "${MK_ORA_SECTIONS[*]}" ]; then
         return
     fi
@@ -2201,9 +2189,10 @@ run_cached () {
         if [ $((now - cf_atime)) -ge $((maxage * 2)) ]; then
             # Kill the process still accessing that file in case
             # it is still running. This avoids overlapping processes!
-            fuser -k -9 "${cache_file}.new" >/dev/null 2>&1
-            rm -f "${cache_file}.new"
-            logging "[${MK_SID}] [run_cached]" "Creation of the cache takes suspiciously long"
+            if ! $MK_ORA_LOGGING; then
+                fuser -k -9 "${cache_file}.new" >/dev/null 2>&1
+                rm -f "${cache_file}.new"
+            fi
             return
         fi
     fi
@@ -2222,7 +2211,11 @@ run_cached () {
 
     # Cache file outdated and new job not yet running? Start it
     if [ -z "$use_cache_file" ] && [ ! -e "${cache_file}.new" ]; then
-        logging "[${MK_SID}] [run_cached]" "Cache file outdated, start it."
+        if $MK_ORA_LOGGING; then
+            logging "[${MK_SID}] [run_cached]" "Cache file outdated, new cache file would be created if logging disabled. Skip"
+            return
+        fi
+
         if $MK_ORA_DEBUG; then
             echo "set -o noclobber; exec > \"${cache_file}.new\" || exit 1; ${cmd_name} && mv \"${cache_file}.new\" \"${cache_file}\" || rm -f \"${cache_file}\" \"${cache_file}.new\"" | /bin/bash
         else
@@ -2445,9 +2438,11 @@ mk_ora_sqlplus () {
         logging "[${MK_SID}] [${from_where}] [mk_ora_sqlplus]" "Elapsed time: $elapsed_time"
 
     else
-        logging -w "[${MK_SID}] [${from_where}] [mk_ora_sqlplus]" "OUTPUT '$output'"
         output=$(echo -e "$output" | "${GREP}" -v "^ERROR at line" | tr '\n' ' ' |\
                                      sed "s/^/$(echo "$MK_SID" | tr '[:lower:]' '[:upper:]')|FAILURE|/" ; echo)
+
+        logging -w "[${MK_SID}] [${from_where}] [mk_ora_sqlplus]" "Found '^ERROR at line'"
+
         if $MK_ORA_DEBUG_CONNECT; then
             echo "Logindetails: ${DBCONNECT}" >&2
             echo -e "$output"
@@ -2551,28 +2546,31 @@ do_checks () {
                     sections=${sections:+"$sections "}"${section}"
                 fi
             done; echo "$sections")
-        logging "[${MK_SID}] [do_checks]" "Do single sections: $sections"
 
         MK_SYNC_SECTIONS_QUERY=$(for section in $sections; do eval "sql_$section" ; done)
         MK_ASYNC_SECTIONS_QUERY=
+
+        logging "[${MK_SID}] [do_checks]" "Execute explicit sections: $sections"
 
     else
         excluded=$(eval "echo \$EXCLUDE_$MK_SID")
         sections=$(remove_excluded_sections "$do_sync_sections" "$excluded")
         asections=$(remove_excluded_sections "$do_async_sections" "$excluded")
-        logging "[${MK_SID}] [do_checks]" "Excluded: $excluded"\
-                "Sections: $sections" "Async sections: $asections"
 
-        MK_SYNC_SECTIONS_QUERY=$(for section in $sections; do eval "sql_$section" ; done)
-        MK_ASYNC_SECTIONS_QUERY=$(for section in $asections; do eval "sql_$section" ; done)
+        if $MK_ORA_LOGGING; then
+            MK_SYNC_SECTIONS_QUERY=$(for section in $sections $asections; do eval "sql_$section" ; done)
+            MK_ASYNC_SECTIONS_QUERY=
+        else
+            MK_SYNC_SECTIONS_QUERY=$(for section in $sections; do eval "sql_$section" ; done)
+            MK_ASYNC_SECTIONS_QUERY=$(for section in $asections; do eval "sql_$section" ; done)
+
+        fi
+
+        logging "[${MK_SID}] [do_checks]" "Note: async sections are executed as sync sections"\
+                "Excluded: $excluded" "Sections: $sections" "Async sections: $asections"
 
     fi
     export MK_ASYNC_SECTIONS_QUERY
-
-    if $MK_ORA_LOGGING; then
-        logging "[${MK_SID}] [do_checks]" "Testmode: $(echo \
-                "select user || ' on ' || host_name || ' instance ' || instance_name from v\$instance;" | mk_ora_sqlplus "do_checks")"
-    fi
 
     if $MK_ORA_DEBUG_CONNECT; then
         do_testmode "$sections" "$asections" 2>&1
