15970 FIX mk_oracle: Fix "Database or necessary processes not running or login failed" error due to race conditions
mk_oracle stores the query results for SYNC_SECTIONS in intermediate cache files per SID, which will be cleaned up afterwards.
Currently, these files can be erroneously deleted before the agent plugin has finished if the agent plugin is started a second time, resulting in a "Database or necessary processes not running or login failed" error.
This has been fixed by only deleting files created by the current process.

SUP-14813

Change-Id: Iff193dd842f72d4ddbb7652f9dbc1434494e2492

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -2944,6 +2944,7 @@ export -f handle_custom_sql_errors
 
 set_up_tmpdirs() {
     ORA_TMPDIR="${MK_VARDIR}/tmp/mk_oracle_tmp_dir"
+    # why don't we use /tmp to make cleanup easier?
     ORA_TASKS_TMPDIR="${ORA_TMPDIR}/tasks"
     mkdir -p "$ORA_TASKS_TMPDIR"
 }
@@ -3025,6 +3026,9 @@ main_queries() {
         _QUERY_PREFIX=$$
     fi
 
+    logging "[local] setting up intermediate query result directory '${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX}'"
+    mkdir -p "${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX}"
+
     TASK_NR=0
     for sid in $SIDS; do
         if skip_sid "$sid"; then
@@ -3033,7 +3037,9 @@ main_queries() {
         fi
         ((TASK_NR++))
         logging "[${sid}] [local] starting background task '${TASK_NR}'"
-        (execute_queries_for_sid "$sid" >"$ORA_TASKS_TMPDIR/${_QUERY_PREFIX}-$sid") &
+        SID_QUERY_FILE="${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX}/SID-$sid"
+
+        (execute_queries_for_sid "$sid" >"${SID_QUERY_FILE}") &
         if [[ $(jobs -r -p | wc -l) -ge ${MAX_TASKS} ]]; then
             logging "[${sid}] [local] max parallel task running, waiting for new slot"
             if ((BASH_VERSINFO[0] > 4 || BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 3)); then
@@ -3042,12 +3048,24 @@ main_queries() {
                 wait
             fi
         fi
+
+        if [ ! -f "${SID_QUERY_FILE}" ]; then
+            logging "[local] No intermediate query result file '${SID_QUERY_FILE}' exists"
+        fi
     done
 
     wait
 
-    cat "$ORA_TASKS_TMPDIR/${_QUERY_PREFIX}"*
-    rm -f "$ORA_TASKS_TMPDIR"/*
+    cat "${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX}/SID"*
+
+    cleanup_queries() {
+        logging "[local] cleaning up intermediate query result directory '${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX}'"
+        rm -rf "${ORA_TASKS_TMPDIR}/${_QUERY_PREFIX:?}" >/dev/null 2>&1
+        logging "[local] cleaning up any old query result directories in '${ORA_TASKS_TMPDIR}'"
+        # in case process was previously stopped via kill -9 and could not clean up
+        find "${ORA_TASKS_TMPDIR}/*" -type d -mtime +1 -exec rm -r {} + >/dev/null 2>&1
+    }
+    trap cleanup_queries HUP INT QUIT ABRT ALRM TERM EXIT
 
     #   ---remote---------------------------------------------------------------
 
