14447 FIX mk_oracle: Cleanup long running processes on AIX
Change-Id: I619c43171215c715e8788c70819a68a232e0f15d

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -372,10 +372,6 @@ unsupported_os() {
     exit 1
 }
 
-file_mtime() {
-    /usr/bin/perl -e 'if (! -f $ARGV[0]){die "0000000"};$mtime=(stat($ARGV[0]))[9];print ($mtime);' "$1"
-}
-
 set_os_env() {
     if [ "$OS_TYPE" = 'Linux' ]; then
         GREP="grep"
@@ -408,22 +404,29 @@ set_os_env() {
     export GREP AWK
 }
 
-mk_ora_atime() {
-    case $OS_TYPE in
-        Linux) stat -c %X "$@" ;;
-        SunOS | AIX) file_mtime "$@" ;;
-        HP-UX) perl -le 'print((stat shift)[8])' "$@" ;;
-        *) unsupported_os ;;
-    esac
+set_up_get_epoch() {
+    # On some systems date +%s returns a literal %s
+    if date +%s | grep "^[0-9].*$" >/dev/null 2>&1; then
+        get_epoch() { date +%s; }
+    else
+        # do not check whether perl is even present.
+        # in weird cases we may be fine without get_epoch.
+        get_epoch() { perl -e 'print($^T."\n");'; }
+    fi
 }
 
-mk_ora_mtime() {
-    case $OS_TYPE in
-        Linux) stat -c %Y "$@" ;;
-        SunOS | AIX) file_mtime "$@" ;;
-        HP-UX) perl -le 'print((stat shift)[9])' "$@" ;;
-        *) unsupported_os ;;
-    esac
+# Please keep this in sync with the agents!
+get_file_atime() {
+    stat -c %X "${1}" 2>/dev/null ||
+        stat -f %a "${1}" 2>/dev/null ||
+        perl -e 'if (! -f $ARGV[0]){die "0000000"};$atime=(stat($ARGV[0]))[8];print $atime."\n";' "${1}"
+}
+
+# Please keep this in sync with the agents!
+get_file_mtime() {
+    stat -c %Y "${1}" 2>/dev/null ||
+        stat -f %m "${1}" 2>/dev/null ||
+        perl -e 'if (! -f $ARGV[0]){die "0000000"};$mtime=(stat($ARGV[0]))[9];print $mtime."\n";' "${1}"
 }
 
 #.
@@ -2387,56 +2390,70 @@ run_cached() {
         return
     fi
 
-    local maxage="$1"
-    local cmd_name="$2"
+    NAME="oracle_${MK_SID}${3}"
+    MAXAGE="${1}"
+    CMD="${2}"
 
-    local cache_file="$MK_VARDIR/cache/oracle_${MK_SID}${3}.cache"
-    local use_cache_file=
-    local now=
-    local cf_atime=
-    local mtime=
+    TIMEOUT=$((MAXAGE * 2))
+    REFRESH_INTERVAL="${MAXAGE}"
 
-    if [ ! -d "$MK_VARDIR/cache" ]; then
-        mkdir -p "$MK_VARDIR/cache"
-    fi
+    [ -d "${MK_VARDIR}/cache" ] || mkdir -p "${MK_VARDIR}/cache"
+    CACHEFILE="${MK_VARDIR}/cache/${NAME}.cache"
 
-    # Check if the creation of the cache takes suspiciously long and return
-    # nothing if the age (access time) of $cache_file.new is twice the 'maxage'
-    # perl is needed for Solaris => no date +%s availible
-    now=$(perl -le "print time()")
-    if [ -e "${cache_file}.new" ]; then
-        cf_atime=$(mk_ora_atime "${cache_file}.new")
-        if [ $((now - cf_atime)) -ge $((maxage * 2)) ]; then
-            # Kill the process still accessing that file in case
-            # it is still running. This avoids overlapping processes!
-            if ! $MK_ORA_LOGGING; then
-                fuser -k -9 "${cache_file}.new" >/dev/null 2>&1
-                rm -f "${cache_file}.new"
-            fi
-            return
-        fi
-    fi
+    NOW="$(get_epoch)"
+    MTIME=$(get_file_mtime "${CACHEFILE}" 2>/dev/null) || MTIME=0
 
-    # Check if cache file exists and is recent enough
-    if [ -s "$cache_file" ]; then
-        mtime=$(mk_ora_mtime "$cache_file")
-        if [ $((now - mtime)) -le "$maxage" ]; then
-            use_cache_file=1
-        fi
-        # Output the file in any case, even if it is
-        # outdated. The new file will not yet be available
-        sed "s/^<<<\\(.*\\)>>>$/<<<\\1:cached(${mtime},${maxage})>>>/g" "$cache_file"
-    fi
+    if [ -s "${CACHEFILE}" ]; then
 
-    # Cache file outdated and new job not yet running? Start it
-    if [ -z "$use_cache_file" ] && [ ! -e "${cache_file}.new" ]; then
-        if $MK_ORA_DEBUG; then
-            echo "set -o noclobber; exec > \"${cache_file}.new\" || exit 1; ${cmd_name} && mv \"${cache_file}.new\" \"${cache_file}\" || rm -f \"${cache_file}\" \"${cache_file}.new\"" | /bin/bash
+        # Output the file (even if it is outdated)
+        CACHE_INFO="cached(${MTIME},${MAXAGE})"
+        if [ "${NAME%%_*}" = "local" ] || [ "${NAME%%_*}" = "mrpe" ]; then
+            # prefix CACHE_INFO, but skip any headers and lines with existing CACHE_INFO
+            sed -e '/^<<<.*>>>/{p;d;}' -e "/^cached([0-9]*,[0-9]*) /{p;d;}; s/^/${CACHE_INFO} /" "${CACHEFILE}"
         else
-            # When the command fails, the output is throws away ignored
-            echo "set -o noclobber; exec > \"${cache_file}.new\" || exit 1; ${cmd_name} && mv \"${cache_file}.new\" \"${cache_file}\" || rm -f \"${cache_file}\" \"${cache_file}.new\"" | nohup /bin/bash >/dev/null 2>&1 &
+            # insert CACHE_INFO in header, but skip headers with existing CACHE_INFO
+            sed -e '/^<<<.*\(:cached(\).*>>>/{p;d;}' -e 's/^<<<\([^>]*\)>>>$/<<<\1:'"${CACHE_INFO}"'>>>/' "${CACHEFILE}"
+        fi
+
+    fi
+
+    # Check if the creation of the cache takes suspiciously long.
+    # Kill the process if the cache file has not been accessed for more than TIMEOUT seconds.
+    for cfile in "${CACHEFILE}.new."*; do
+        [ -e "${cfile}" ] || break # no match
+        if [ $((NOW - $(get_file_atime "${cfile}"))) -ge "${TIMEOUT}" ]; then
+            kill -9 "${cfile##*.new.}" # TODO: what about child processes?
+            rm -f "${cfile}" "${CACHEFILE}"
+        fi
+    done
+
+    # This does the right thing, regardless whether the pattern matches!
+    _cfile_in_use() {
+        for cfile in "${CACHEFILE}.new."*; do
+            printf "%s\n" "${cfile}"
+            break
+        done
+    }
+
+    # Time to refresh cache file and new job not yet running?
+    if [ $((NOW - MTIME)) -gt "${REFRESH_INTERVAL}" ] && [ ! -e "$(_cfile_in_use)" ]; then
+        THIS_SHELL="$(ps -o args= -p $$ | sed -e 's/^-//' -e 's/\ .*//')"
+        # Start it. If the command fails the output is thrown away
+        if $MK_ORA_DEBUG; then
+            cat <<HERE | "${THIS_SHELL}"
+exec > "${CACHEFILE}.new.\$\$" || exit 1
+${CMD} && mv "${CACHEFILE}.new.\$\$" "${CACHEFILE}" || rm -f "${CACHEFILE}" "${CACHEFILE}.new.\$\$"
+HERE
+        else
+            cat <<HERE | nohup "${THIS_SHELL}" >/dev/null 2>&1 &
+exec > "${CACHEFILE}.new.\$\$" || exit 1
+${CMD} && mv "${CACHEFILE}.new.\$\$" "${CACHEFILE}" || rm -f "${CACHEFILE}" "${CACHEFILE}.new.\$\$"
+HERE
+
         fi
     fi
+
+    unset NAME MAXAGE TIMEOUT REFRESH_INTERVAL CACHEFILE MTIME CACHE_INFO NOW
 }
 
 #.
@@ -2891,6 +2908,8 @@ logging "--------------------------------------------------------------------"
 
 #   ---preliminaries--------------------------------------------------------
 set_os_env
+
+set_up_get_epoch
 
 # Get list of all running databases. Do not work on ASM in this plugin.
 # => Ignore a running ASM-Instance!
