15759 FIX mk_oracle: Fix error in the mk_oracle plugin
Werk 15848 (version 2.1.0p29) introduced a bug which caused the mk_oracle
plugin to execute incorrectly and stop sending data to Checkmk.

If called from the command line from the plugin's parent directory, the plugin
incorrectly reported `Unhandled location` and terminated, even if the location
of the plugin was correct.

SUP-14507

Change-Id: I2d3b4b4e8eef3bd7ca3709efd995ef6b245f5128

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -3062,11 +3062,13 @@ main_queries() {
 main() {
     # See werk 13732 for more details about this main function
 
-    if [ "$0" = "./mk_oracle" ]; then
-        parent_dir=$(basename "$(pwd)")
-    else
-        parent_dir=$(basename "$(dirname "$0")")
-    fi
+    parent_dir=$(basename "$(
+        cd "$(dirname "$0")" || {
+            echo "Can't access the parent directory" >&2
+            exit 1
+        }
+        pwd
+    )")
 
     if $MK_ORA_ON_CL || [ "$parent_dir" = plugins ]; then
         # Does not work properly (async sections) on distros
