Add missing error redirection
If DB is not available and MK_ORA_DEBUG_CONNECT is set, the output with Errormessage is going to stdout like this:

    Error Message:          ORADB|FAILURE|ERROR: ORA-28000: Account is locked.   SP2-0751: Unable to connect to Oracle.  Exit

Creating a dummy Service "Error Message"

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -2820,7 +2820,7 @@ EOM
 
         if $MK_ORA_DEBUG_CONNECT; then
             echo "    Logindetails:           ${MK_DB_CONNECT}" >&2
-            echo -e "    Error Message:          ${output:0:100}"
+            echo -e "    Error Message:          ${output:0:100}" >&2
         else
             echo '<<<oracle_instance:sep(124)>>>'
             echo -e "$output"
