ORACLE: new version check, improve error handling

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -27,8 +27,23 @@
 
 # Get list of all running databases
 SIDS=$(UNIX95=true ps ax -o args | sed -n '/^\(ora\|xe\)_pmon_\([^ ]*\)/s//\2/p')
-if [ -z "$SIDS" ] ; then exit 0 ; fi
+if [ -z "$SIDS" ] ; then 
+    # If on this system we've already found a database
+    if [ -e "$MK_CONFDIR/mk_oracle.found" ] ; then
+        echo '<<<oracle_version>>>'
+        echo '<<<oracle_sessions>>>'
+        echo '<<<oracle_logswitches>>>'
+        echo '<<<oracle_tablespaces>>>'
+    fi
+    exit 0
+fi
 
+touch $MK_CONFDIR/mk_oracle.found
+
+# Recreate data if cachefile is older than 120 seconds.
+# If you set this to 0, then the cache file will be created
+# as often as possible. If the database queries last longer
+# then your check interval, caching will be active nevertheless.
 CACHE_MAXAGE=120
 
 # Source the optional configuration file for this agent plugin
@@ -61,12 +76,29 @@ fi
 # The cache is used for $CACHE_MAXAGE seconds. The CACHE_MAXAGE
 # option is pre-set to 120 seconds but can be changed in mk_oracle.cfg.
 
+function sqlplus ()
+{
+    if OUTPUT=$({ echo 'set pages 0' ; echo 'whenever sqlerror exit 1'; echo 'set lines 8000' ; echo 'set feedback off'; cat ; } | $MK_CONFDIR/sqlplus.sh $1)
+    then
+        echo "${OUTPUT}" | sed -e 's/[[:space:]]\+/ /g' -e '/^[[:space:]]*$/d' -e "s/^/$1 /"
+    else
+        echo "${OUTPUT}" | sed "s/^/$1 FAILURE /"
+    fi
+}
+
+
 for SID in $SIDS; do
     EXCLUDE=EXCLUDE_$SID
     EXCLUDE=${!EXCLUDE}
     # SID filtered totally?
     if [ "$EXCLUDE" = "ALL" ]; then
         continue
+    fi
+
+    # Do Version-Check (use as a general login check) without caching
+    if [ "$EXCLUDE" = "${EXCLUDE/oracle_version/}" ]; then
+        echo '<<<oracle_version>>>'
+        echo "select banner from v\$version where banner like 'Oracle%';" | sqlplus "$SID"
     fi
 
     CACHE_FILE=$MK_CONFDIR/oracle_$SID.cache
@@ -82,12 +114,13 @@ for SID in $SIDS; do
     fi
 
     # If the cache file exists, output it, regardless of its age. If it's outdated
-    # then it will be recreated *asynchronously*, we the new contents will not 
+    # then it will be recreated *asynchronously*. It's new contents will not 
     # be available here anyway.
     if [ -s "$CACHE_FILE" ] ; then cat "$CACHE_FILE" ; fi
 
-    # When not it checks if there is another task to update the cache is running
-    # at the moment (*.new) file present.
+    # When the cache file is not valid, we recreated it, but only if there is not    
+    # yet a background process from a previous check still doing this! We see this
+    # because of the existance of the .new file
     # When the cache is old and there is no *new file present, then start a query
     # to update the information for this instance.
     if [ -z "$USE_CACHE_FILE" -a ! -e "$CACHE_FILE.new" ]
@@ -96,25 +129,24 @@ for SID in $SIDS; do
             set -o noclobber
             function sqlplus ()
             {
-                OUTPUT=\$({ echo 'set pages 0' ; echo 'set lines 8000' ; echo 'set feedback off'; cat ; } | $MK_CONFDIR/sqlplus.sh \$1) || return 1
-                echo \"\${OUTPUT}\" | sed -e 's/[[:space:]]\+/ /g' -e '/^[[:space:]]*$/d' -e \"s/^/\$1 /\"
+                if OUTPUT=\$({ echo 'set pages 0' ; echo 'whenever sqlerror exit 1'; echo 'set lines 8000' ; echo 'set feedback off'; cat ; } | $MK_CONFDIR/sqlplus.sh \$1)
+		then
+                    echo \"\${OUTPUT}\" | sed -e 's/[[:space:]]\+/ /g' -e '/^[[:space:]]*$/d' -e \"s/^/\$1 /\"
+		else
+		    echo \"\${OUTPUT}\" | sed \"s/^/\$1 FAILURE /\"
+                fi
             }
 
             {
             # Only execute checks when not filtered
-            if [ "$EXCLUDE" = "${EXCLUDE/oracle_version/}" ]; then
-                echo '<<<oracle_version>>>'
-                echo \"select banner from v\\\$version where banner like 'Oracle%';\" | sqlplus \"$SID\"
-            fi
-
             if [ "$EXCLUDE" = "${EXCLUDE/oracle_sessions/}" ]; then
                 echo '<<<oracle_sessions>>>'
-                echo \"select count(*) from v\\\$session where status = 'ACTIVE';\" | sqlplus \"$SID\"
+                echo \"select count(1) from v\\\$session where status = 'ACTIVE';\" | sqlplus \"$SID\"
             fi
 
             if [ "$EXCLUDE" = "${EXCLUDE/oracle_logswitches/}" ]; then
                 echo '<<<oracle_logswitches>>>'
-                echo \"select count(*) from v\\\$loghist where first_time > sysdate - 1/24;\" | sqlplus \"$SID\"
+                echo \"select count(1) from v\\\$loghist where first_time > sysdate - 1/24;\" | sqlplus \"$SID\"
             fi
 
             if [ "$EXCLUDE" = "${EXCLUDE/oracle_tablespaces/}" ]; then
