12815 FIX mk_oracle: errors are not written to cache file
The agent plugin mk_oracle does not create a cache file any more in case of error.
In previous versions the content of the cache file could contain an error message like:
"Error Message:          ABC|FAILURE|ERROR:ORA-01017: invalid username/password;..."
You have to redeploy the agent plugin in order to apply this bugfix.

Change-Id: Ie79769745e4e21700dc04e5ca3e3d6d364bb8734

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -2694,7 +2694,7 @@ mk_ora_sqlplus () {
 
         if $MK_ORA_DEBUG_CONNECT; then
             echo "    Logindetails:           ${MK_DB_CONNECT}" >&2
-            echo -e "    Error Message:          ${output:0:100}"
+            echo -e "    Error Message:          ${output:0:100}" >&2
         else
             echo '<<<oracle_instance:sep(124)>>>'
             echo -e "$output"
