mk_oracle: Make simple main
- Improve tests
- cleanup foldables

Change-Id: Iaf16f4412df473b46b13170c3ee09cd718f66467

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -43,7 +43,7 @@ load_default_config() {
     MAX_TASKS=1
 }
 
-#.
+# .
 #   .--usage---------------------------------------------------------------.
 #   |                                                                      |
 #   |                     _   _ ___  __ _  __ _  ___                       |
@@ -206,7 +206,7 @@ CONFIGURATION CUSTOM SQLS:
 MK-ORA-USAGE
 }
 
-#.
+# .
 #   .--args----------------------------------------------------------------.
 #   |                                                                      |
 #   |                          __ _ _ __ __ _ ___                          |
@@ -261,7 +261,7 @@ while test -n "$1"; do
     esac
 done
 
-#.
+# .
 #   .--config--------------------------------------------------------------.
 #   |                                      __ _                            |
 #   |                      ___ ___  _ __  / _(_) __ _                      |
@@ -357,7 +357,7 @@ load_config() {
     fi
 }
 
-#.
+# .
 #   .--OS env--------------------------------------------------------------.
 #   |                     ___  ____                                        |
 #   |                    / _ \/ ___|    ___ _ ____   __                    |
@@ -431,7 +431,7 @@ get_file_mtime() {
         perl -e 'if (! -f $ARGV[0]){die "0000000"};$mtime=(stat($ARGV[0]))[9];print $mtime."\n";' "${1}"
 }
 
-#.
+# .
 #   .--logging-------------------------------------------------------------.
 #   |                  _                   _                               |
 #   |                 | | ___   __ _  __ _(_)_ __   __ _                   |
@@ -557,7 +557,7 @@ logging() {
     fi
 }
 
-#.
+# .
 #   .--ORA env-------------------------------------------------------------.
 #   |                ___  ____      _                                      |
 #   |               / _ \|  _ \    / \      ___ _ ____   __                |
@@ -642,7 +642,7 @@ set_ora_version() {
 
 }
 
-#.
+# .
 #   .--SQL Queries---------------------------------------------------------.
 #   |        ____   ___  _        ___                  _                   |
 #   |       / ___| / _ \| |      / _ \ _   _  ___ _ __(_) ___  ___         |
@@ -2086,7 +2086,7 @@ sql_asm_diskgroup() {
     fi
 }
 
-#.
+# .
 #   .--custom SQL----------------------------------------------------------.
 #   |                       _                    ____   ___  _             |
 #   |         ___ _   _ ___| |_ ___  _ __ ___   / ___| / _ \| |            |
@@ -2281,7 +2281,7 @@ handle_custom_sql_errors() {
     fi
 }
 
-#.
+# .
 #   .--helper--------------------------------------------------------------.
 #   |                    _          _                                      |
 #   |                   | |__   ___| |_ __   ___ _ __                      |
@@ -2365,7 +2365,7 @@ ora_session_environment() {
     echo ' '
 }
 
-#.
+# .
 #   .--run cached----------------------------------------------------------.
 #   |                                           _              _           |
 #   |         _ __ _   _ _ __     ___ __ _  ___| |__   ___  __| |          |
@@ -2447,7 +2447,7 @@ HERE
     unset NAME MAXAGE TIMEOUT REFRESH_INTERVAL CACHEFILE MTIME CACHE_INFO NOW
 }
 
-#.
+# .
 #   .--DB connect----------------------------------------------------------.
 #   |          ____  ____                                    _             |
 #   |         |  _ \| __ )    ___ ___  _ __  _ __   ___  ___| |_           |
@@ -2631,7 +2631,7 @@ mk_ora_db_connect() {
 
 }
 
-#.
+# .
 #   .--mk ora sqlplus------------------------------------------------------.
 #   |            _                                  _       _              |
 #   |  _ __ ___ | | __   ___  _ __ __ _   ___  __ _| |_ __ | |_   _ ___    |
@@ -2699,7 +2699,7 @@ mk_ora_sqlplus() {
     fi
 }
 
-#.
+# .
 #   .--do checks-----------------------------------------------------------.
 #   |                 _              _               _                     |
 #   |              __| | ___     ___| |__   ___  ___| | _____              |
@@ -2862,103 +2862,6 @@ do_checks() {
     fi
 }
 
-#.
-#   .--main----------------------------------------------------------------.
-#   |                                       _                              |
-#   |                       _ __ ___   __ _(_)_ __                         |
-#   |                      | '_ ` _ \ / _` | | '_ \                        |
-#   |                      | | | | | | (_| | | | | |                       |
-#   |                      |_| |_| |_|\__,_|_|_| |_|                       |
-#   |                                                                      |
-#   +----------------------------------------------------------------------+
-#   |  Iterate over all instances and execute sync and async sections.     |
-#   '----------------------------------------------------------------------'
-
-# Make sure that the new shell that is being run by run_cached inherits
-# our functions
-export -f logging
-export -f mk_ora_sqlplus
-export -f ora_session_environment
-export -f do_async_checks
-export -f set_ora_env
-export -f unset_custom_sqls_vars
-export -f custom_sql_section
-export -f do_async_custom_sqls
-export -f handle_custom_sql_errors
-
-if $MK_ORA_LOGGING; then
-    # cleanup old leftovers
-    rm -f "${MK_VARDIR}"/log/mk_oracle_task_*.log
-    echo "Logging to file: ${MK_VARDIR}/log/mk_oracle.log" >&2
-fi
-
-logging "--------------------------------------------------------------------"
-
-#   ---preliminaries--------------------------------------------------------
-set_os_env
-
-set_up_get_epoch
-
-# Get list of all running databases. Do not work on ASM in this plugin.
-# => Ignore a running ASM-Instance!
-# shellcheck disable=SC2016
-SIDS=$(UNIX95=true ps -ef | "${AWK}" '{print $NF}' |
-    "${GREP}" -E '^asm_pmon_|^ora_pmon_|^xe_pmon_' |
-    cut -d"_" -f3- | sort)
-
-# Load config AFTER we got the SIDS since we allow users to use this variable in their config
-load_config
-
-# Are there any remote configurations?
-for remote_instance in $(compgen -A variable | "${GREP}" -E "^REMOTE_INSTANCE_.*"); do
-    REMOTE_INSTANCES="${REMOTE_INSTANCES} ${remote_instance}"
-    # shellcheck disable=SC2005
-    PIGGYBACK_HOSTS="$(echo "$(eval "echo \${$remote_instance}")" | cut -d":" -f6) ${PIGGYBACK_HOSTS}"
-done
-
-PIGGYBACK_HOSTS="$(echo "$PIGGYBACK_HOSTS" | tr ' ' '\n' | sort | uniq)"
-
-logging "[preliminaries]" \
-    "SIDs                : ${SIDS//$'\n'/ }" \
-    "Remote instances    : ${REMOTE_INSTANCES}" \
-    "Piggyback hosts     : ${PIGGYBACK_HOSTS//$'\n'/ }" \
-    "OS                  : ${OS_TYPE}" \
-    "SYNC_SECTIONS       : ${SYNC_SECTIONS}" \
-    "ASYNC_SECTIONS      : ${ASYNC_SECTIONS}" \
-    "SYNC_ASM_SECTIONS   : ${SYNC_ASM_SECTIONS}" \
-    "ASYNC_ASM_SECTIONS  : ${ASYNC_ASM_SECTIONS}" \
-    "CACHE_MAXAGE        : ${CACHE_MAXAGE}" \
-    "ONLY_SIDS           : ${ONLY_SIDS}" \
-    "SKIP_SIDS           : ${SKIP_SIDS}" \
-    "Custom SQLs sections: $custom_sqls_sections"
-
-if [ "$PIGGYBACK_HOSTS" ]; then
-    if [ ! -e "$MK_VARDIR/mk_oracle.found" ]; then
-        touch "$MK_VARDIR/mk_oracle.found"
-    fi
-fi
-
-# If we do not have found any running database instance, then either
-# no ORACLE is present on this system or it's just currently not running.
-# In the later case we ouput empty agent sections so that Checkmk will be
-# happy and execute the actual check functions.
-if [ -z "$SIDS" ] && [ ! -e "$MK_VARDIR/mk_oracle.found" ]; then
-    logging -c -e "[preliminaries]" "No SIDs and \$MK_VARDIR/mk_oracle.found not found"
-    exit 1
-fi
-
-# From now on we expect databases on this system (for ever)
-touch "$MK_VARDIR/mk_oracle.found"
-
-# Make sure that always all sections are present, even
-# in case of an error. Note: the section <<<oracle_instance>>>
-# section shows the general state of a database instance. If
-# that section fails for an instance then all other sections
-# do not contain valid data anyway.
-do_dummy_sections
-
-#   ---local----------------------------------------------------------------
-
 execute_queries_for_sid() {
     local sid="$1"
     set_ora_env "$sid"
@@ -2986,62 +2889,165 @@ execute_queries_for_sid() {
     do_custom_sqls
 }
 
-ORA_TMPDIR="${MK_VARDIR}/tmp/mk_oracle"
-mkdir -p "${ORA_TMPDIR}"
-if [ -n "$REMOTE" ]; then
-    _QUERY_PREFIX="${REMOTE}-$$"
-else
-    _QUERY_PREFIX=$$
-fi
+# .
+#   .--main----------------------------------------------------------------.
+#   |                                       _                              |
+#   |                       _ __ ___   __ _(_)_ __                         |
+#   |                      | '_ ` _ \ / _` | | '_ \                        |
+#   |                      | | | | | | (_| | | | | |                       |
+#   |                      |_| |_| |_|\__,_|_|_| |_|                       |
+#   |                                                                      |
+#   +----------------------------------------------------------------------+
+#   |  Iterate over all instances and execute sync and async sections.     |
+#   '----------------------------------------------------------------------'
 
-TASK_NR=0
-for sid in $SIDS; do
-    if skip_sid "$sid"; then
-        logging "[${sid}] [local]" "Skipping this SID"
-        continue
+# Make sure that the new shell that is being run by run_cached inherits
+# our functions
+export -f logging
+export -f mk_ora_sqlplus
+export -f ora_session_environment
+export -f do_async_checks
+export -f set_ora_env
+export -f unset_custom_sqls_vars
+export -f custom_sql_section
+export -f do_async_custom_sqls
+export -f handle_custom_sql_errors
+
+main() {
+    if $MK_ORA_LOGGING; then
+        # cleanup old leftovers
+        rm -f "${MK_VARDIR}"/log/mk_oracle_task_*.log
+        echo "Logging to file: ${MK_VARDIR}/log/mk_oracle.log" >&2
     fi
-    ((TASK_NR++))
-    logging "[${sid}] [local] starting background task '${TASK_NR}'"
-    (execute_queries_for_sid "$sid" >"$ORA_TMPDIR/${_QUERY_PREFIX}-$sid") &
-    if [[ $(jobs -r -p | wc -l) -ge ${MAX_TASKS} ]]; then
-        logging "[${sid}] [local] max parallel task running, waiting for new slot"
-        if ((BASH_VERSINFO[0] > 4 || BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 3)); then
-            wait -n
-        else
-            wait
+
+    logging "--------------------------------------------------------------------"
+
+    #   ---preliminaries--------------------------------------------------------
+
+    set_os_env
+
+    set_up_get_epoch
+
+    # Get list of all running databases. Do not work on ASM in this plugin.
+    # => Ignore a running ASM-Instance!
+    # shellcheck disable=SC2016
+    SIDS=$(UNIX95=true ps -ef | "${AWK}" '{print $NF}' |
+        "${GREP}" -E '^asm_pmon_|^ora_pmon_|^xe_pmon_' |
+        cut -d"_" -f3- | sort)
+
+    # Load config AFTER we got the SIDS since we allow users to use this variable in their config
+    load_config
+
+    # Are there any remote configurations?
+    for remote_instance in $(compgen -A variable | "${GREP}" -E "^REMOTE_INSTANCE_.*"); do
+        REMOTE_INSTANCES="${REMOTE_INSTANCES} ${remote_instance}"
+        # shellcheck disable=SC2005
+        PIGGYBACK_HOSTS="$(echo "$(eval "echo \${$remote_instance}")" | cut -d":" -f6) ${PIGGYBACK_HOSTS}"
+    done
+
+    PIGGYBACK_HOSTS="$(echo "$PIGGYBACK_HOSTS" | tr ' ' '\n' | sort | uniq)"
+
+    logging "[preliminaries]" \
+        "SIDs                : ${SIDS//$'\n'/ }" \
+        "Remote instances    : ${REMOTE_INSTANCES}" \
+        "Piggyback hosts     : ${PIGGYBACK_HOSTS//$'\n'/ }" \
+        "OS                  : ${OS_TYPE}" \
+        "SYNC_SECTIONS       : ${SYNC_SECTIONS}" \
+        "ASYNC_SECTIONS      : ${ASYNC_SECTIONS}" \
+        "SYNC_ASM_SECTIONS   : ${SYNC_ASM_SECTIONS}" \
+        "ASYNC_ASM_SECTIONS  : ${ASYNC_ASM_SECTIONS}" \
+        "CACHE_MAXAGE        : ${CACHE_MAXAGE}" \
+        "ONLY_SIDS           : ${ONLY_SIDS}" \
+        "SKIP_SIDS           : ${SKIP_SIDS}" \
+        "Custom SQLs sections: $custom_sqls_sections"
+
+    if [ "$PIGGYBACK_HOSTS" ]; then
+        if [ ! -e "$MK_VARDIR/mk_oracle.found" ]; then
+            touch "$MK_VARDIR/mk_oracle.found"
         fi
     fi
-done
 
-wait
-cat "$ORA_TMPDIR/${_QUERY_PREFIX}"*
-rm -f "$ORA_TMPDIR"/*
+    # If we do not have found any running database instance, then either
+    # no ORACLE is present on this system or it's just currently not running.
+    # In the later case we ouput empty agent sections so that Checkmk will be
+    # happy and execute the actual check functions.
+    if [ -z "$SIDS" ] && [ ! -e "$MK_VARDIR/mk_oracle.found" ]; then
+        logging -c -e "[preliminaries]" "No SIDs and \$MK_VARDIR/mk_oracle.found not found"
+        exit 1
+    fi
 
-#   ---remote---------------------------------------------------------------
+    # From now on we expect databases on this system (for ever)
+    touch "$MK_VARDIR/mk_oracle.found"
 
-for remote_instance in $REMOTE_INSTANCES; do
-    remote_instance_line=$(eval "echo \${$remote_instance}")
+    # Make sure that always all sections are present, even
+    # in case of an error. Note: the section <<<oracle_instance>>>
+    # section shows the general state of a database instance. If
+    # that section fails for an instance then all other sections
+    # do not contain valid data anyway.
+    do_dummy_sections
 
-    set_ora_env "$remote_instance"
-    set_ora_version "$(echo "$remote_instance_line" | cut -d":" -f8)"
-    logging "[${remote_instance}] [remote]" \
-        "ORACLE_SID      : ${ORACLE_SID}" \
-        "ORACLE_HOME     : ${ORACLE_HOME}" \
-        "TNS_ADMIN       : ${TNS_ADMIN}" \
-        "LD_LIBRARY_PATH : ${LD_LIBRARY_PATH}" \
-        "ORACLE_VERSION  : ${ORACLE_VERSION} (${NUMERIC_ORACLE_VERSION})"
+    #   ---local----------------------------------------------------------------
 
-    db_connect=$(mk_ora_db_connect "$remote_instance")
-    piggyback_host=$(echo "${remote_instance_line}" | cut -d":" -f6)
-    export MK_SID=$remote_instance
-    export MK_DB_CONNECT=$db_connect
-    export MK_PIGGYBACK_HOST=$piggyback_host
+    ORA_TMPDIR="${MK_VARDIR}/tmp/mk_oracle"
+    mkdir -p "${ORA_TMPDIR}"
+    if [ -n "$REMOTE" ]; then
+        _QUERY_PREFIX="${REMOTE}-$$"
+    else
+        _QUERY_PREFIX=$$
+    fi
 
-    do_checks
-    do_custom_sqls
-done
+    TASK_NR=0
+    for sid in $SIDS; do
+        if skip_sid "$sid"; then
+            logging "[${sid}] [local]" "Skipping this SID"
+            continue
+        fi
+        ((TASK_NR++))
+        logging "[${sid}] [local] starting background task '${TASK_NR}'"
+        (execute_queries_for_sid "$sid" >"$ORA_TMPDIR/${_QUERY_PREFIX}-$sid") &
+        if [[ $(jobs -r -p | wc -l) -ge ${MAX_TASKS} ]]; then
+            logging "[${sid}] [local] max parallel task running, waiting for new slot"
+            if ((BASH_VERSINFO[0] > 4 || BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 3)); then
+                wait -n
+            else
+                wait
+            fi
+        fi
+    done
 
-if ${MK_ORA_LOGGING}; then
-    cat "${MK_VARDIR}"/log/mk_oracle_task_*.log >>"${MK_VARDIR}"/log/mk_oracle.log
-    rm -f "${MK_VARDIR}"/log/mk_oracle_task_*.log
-fi
+    wait
+    cat "$ORA_TMPDIR/${_QUERY_PREFIX}"*
+    rm -f "$ORA_TMPDIR"/*
+
+    #   ---remote---------------------------------------------------------------
+
+    for remote_instance in $REMOTE_INSTANCES; do
+        remote_instance_line=$(eval "echo \${$remote_instance}")
+
+        set_ora_env "$remote_instance"
+        set_ora_version "$(echo "$remote_instance_line" | cut -d":" -f8)"
+        logging "[${remote_instance}] [remote]" \
+            "ORACLE_SID      : ${ORACLE_SID}" \
+            "ORACLE_HOME     : ${ORACLE_HOME}" \
+            "TNS_ADMIN       : ${TNS_ADMIN}" \
+            "LD_LIBRARY_PATH : ${LD_LIBRARY_PATH}" \
+            "ORACLE_VERSION  : ${ORACLE_VERSION} (${NUMERIC_ORACLE_VERSION})"
+
+        db_connect=$(mk_ora_db_connect "$remote_instance")
+        piggyback_host=$(echo "${remote_instance_line}" | cut -d":" -f6)
+        export MK_SID=$remote_instance
+        export MK_DB_CONNECT=$db_connect
+        export MK_PIGGYBACK_HOST=$piggyback_host
+
+        do_checks
+        do_custom_sqls
+    done
+
+    if ${MK_ORA_LOGGING}; then
+        cat "${MK_VARDIR}"/log/mk_oracle_task_*.log >>"${MK_VARDIR}"/log/mk_oracle.log
+        rm -f "${MK_VARDIR}"/log/mk_oracle_task_*.log
+    fi
+
+}
+
+[ -z "${MK_SOURCE_ONLY}" ] && main
