Add help text
Change-Id: I81af5afffd37693488e8fc4c8a0be37f899612a7

diff --git a/agents/plugins/mk_oracle b/agents/plugins/mk_oracle
--- a/agents/plugins/mk_oracle
+++ b/agents/plugins/mk_oracle
@@ -82,6 +82,11 @@ while test -n "$1"; do
             if type flock > /dev/null 2>&1; then
                 MK_ORA_LOGGING=1
                 export MK_ORA_LOGGING
+            else
+                echo "You cannot use the option '--log': flock needs to be installed."
+                echo "Please run mk_oracle without '--log'."
+                display_usage >&2
+                exit 2
             fi
             shift
             ;;
