17079 FIX mk_redis: Autodetect Checkmk instances
Previously the redis agent plugin configured to autodetect would not detect the Checkmk redis instances.
Now, on hosts running a Checkmk site, these instances can be autodetected as well and monitored as any other redis instance.

SUP-19026
CMK-7313

Change-Id: I082c9c3456c076d24c63fc991b9604e63a909eeb

diff --git a/agents/plugins/mk_redis b/agents/plugins/mk_redis
--- a/agents/plugins/mk_redis
+++ b/agents/plugins/mk_redis
@@ -76,7 +76,7 @@ main() {
     if [ ${#REDIS_INSTANCES[@]} -eq 0 ]; then
         IS_DETECTED=true
         # find instances and remove entries like "*:6879", possible with docker container
-        DETECTED=$(pgrep -xa "redis-server" 2>/dev/null | awk '/:[0-9]+/ && !/\*/ { print $3 }')
+        DETECTED=$(pgrep -xa "redis-server" 2>/dev/null | awk '/:[0-9]+/ && !/\*/ || /unixsocket:.*/ { print $3 }')
 
         # add found redis instances
         for REDIS_INSTANCE in $DETECTED; do
@@ -84,11 +84,17 @@ main() {
                 IFS=":" read -ra parts <<<"$inst"
 
                 # dot of IP can not be used in variable names
-                REDIS_NAME=$(echo "$inst" | tr :. _)
+                REDIS_NAME=$(echo "$inst" | tr ':./' '_')
 
                 # create dynamic variables
-                declare "REDIS_HOST_$REDIS_NAME=${parts[0]}"
-                declare "REDIS_PORT_$REDIS_NAME=${parts[1]}"
+                if [[ "${parts[0]}" == "unixsocket" ]]; then
+                    # handle checkmk redis instances as configured sockets
+                    declare "REDIS_HOST_$REDIS_NAME=${parts[1]}"
+                    declare "REDIS_PORT_$REDIS_NAME=unix-socket"
+                else
+                    declare "REDIS_HOST_$REDIS_NAME=${parts[0]}"
+                    declare "REDIS_PORT_$REDIS_NAME=${parts[1]}"
+                fi
 
                 # append instance to array
                 REDIS_INSTANCES+=("${REDIS_NAME}")
@@ -106,9 +112,21 @@ main() {
         # print server section
         echo "[[[$INSTANCE|${!HOST}|${!PORT}]]]"
 
-        # execute command
-        waitmax 3 bash -c "${REDIS_CLI_COMMAND} ${REDIS_ARGS[*]}" || true
-        echo
+        if [[ "${!HOST}" == /omd/sites/* ]]; then
+            # use site redis-cli for redis instances in site
+            IFS="/" read -ra ADDR <<<"${!HOST}"
+            output=$(waitmax 3 bash -c "/omd/sites/${ADDR[3]}/bin/redis-cli ${REDIS_ARGS[*]}" 2>&1 || true)
+        else
+            output=$(waitmax 3 bash -c "${REDIS_CLI_COMMAND} ${REDIS_ARGS[*]}" 2>&1 || true)
+        fi
+
+        if [[ "$output" == *"Could not connect to Redis at ${!HOST}: Permission denied"* ]]; then
+            # mark error explicitly for easier parsing
+            echo "error: $output"
+        else
+            echo "$output"
+        fi
+
     done
 
 }
