FIX 15467 sap_hana: Enable clustering of active and passive nodes
Previously, we collected data only for databases in primary and
logreplay_readaccess replication modes. For other replication modes
only SAP HANA Status service was shown.

In order to enable clustering of active and passive nodes,
we now try to collect data for all replication modes and if the database
cannot be accessed, the services of that host will go to STALE.

SUP-4970

Change-Id: Id3e26260a3707bf5997302ef54a2c72806c7d2d9

diff --git a/agents/plugins/mk_sap_hana b/agents/plugins/mk_sap_hana
--- a/agents/plugins/mk_sap_hana
+++ b/agents/plugins/mk_sap_hana
@@ -585,12 +585,6 @@ get_instance_user() {
 
 }
 
-get_operation_mode() {
-    local instance_user="$1"
-    result="$(su - "${instance_user}" -c "hdbnsutil -sr_state")"
-    echo "$result" | grep "operation mode" | awk -F ' ' '{print $3}'
-}
-
 read_global_ini() {
     local sid=$1
     content="$(cat "/usr/sap/${sid}/SYS/global/hdb/custom/config/global.ini")"
@@ -827,49 +821,36 @@ if [ -n "$DBS" ]; then
             INSTANCE_USER=$(get_instance_user "$SID" "$INSTANCE")
             set_sap_hana_version "$INSTANCE_USER"
 
-            replication_mode=$(get_operation_mode "$INSTANCE_USER")
-            if [ -z "$replication_mode" ] || [ "$replication_mode" = "primary" ] || [ "$replication_mode" = "logreplay_readaccess" ]; then
+            SAP_LANDSCAPE=$(su - "${INSTANCE_USER}" -c "python /usr/sap/${SID}/HDB${INSTANCE}/exe/python_support/landscapeHostConfiguration.py")
+            HOSTNAME=$(sap_hana_host_from_landscape "$SAP_LANDSCAPE")
+            SSLOPTION=$(get_ssl_option "$SID" "$HOSTNAME")
 
-                SAP_LANDSCAPE=$(su - "${INSTANCE_USER}" -c "python /usr/sap/${SID}/HDB${INSTANCE}/exe/python_support/landscapeHostConfiguration.py")
-                HOSTNAME=$(sap_hana_host_from_landscape "$SAP_LANDSCAPE")
-                SSLOPTION=$(get_ssl_option "$SID" "$HOSTNAME")
-
-                # find the first db that is connected for queries that should be run per instance
-                for DB_DATA in "${DBS[@]}"; do
-                    IFS=',' read -r db_sid db_instance db_name db_user db_password db_userstorekey <<<"${DB_DATA}"
-                    if [ "$SID" == "$db_sid" ] && [ "$INSTANCE" == "$db_instance" ]; then
-                        CREDENTIALS=$(get_credentials "${db_user}" "${db_password}" "${db_userstorekey}")
-                        if database_connected "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$CREDENTIALS" "$SSLOPTION"; then
-                            break
-                        fi
+            # find the first db that is connected for queries that should be run per instance
+            for DB_DATA in "${DBS[@]}"; do
+                IFS=',' read -r db_sid db_instance db_name db_user db_password db_userstorekey <<<"${DB_DATA}"
+                if [ "$SID" == "$db_sid" ] && [ "$INSTANCE" == "$db_instance" ]; then
+                    CREDENTIALS=$(get_credentials "${db_user}" "${db_password}" "${db_userstorekey}")
+                    if database_connected "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$CREDENTIALS" "$SSLOPTION"; then
+                        break
                     fi
-                done
+                fi
+            done
 
-                query_instance "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$SAP_LANDSCAPE" "$db_name" "$CREDENTIALS" "$SSLOPTION"
+            query_instance "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$SAP_LANDSCAPE" "$db_name" "$CREDENTIALS" "$SSLOPTION"
 
-                for DB_DATA in "${DBS[@]}"; do
-                    IFS=',' read -r db_sid db_instance db_name db_user db_password db_userstorekey <<<"${DB_DATA}"
-                    if [ "$SID" == "$db_sid" ] && [ "$INSTANCE" == "$db_instance" ]; then
-                        CREDENTIALS=$(get_credentials "${db_user}" "${db_password}" "${db_userstorekey}")
+            for DB_DATA in "${DBS[@]}"; do
+                IFS=',' read -r db_sid db_instance db_name db_user db_password db_userstorekey <<<"${DB_DATA}"
+                if [ "$SID" == "$db_sid" ] && [ "$INSTANCE" == "$db_instance" ]; then
+                    CREDENTIALS=$(get_credentials "${db_user}" "${db_password}" "${db_userstorekey}")
 
-                        if database_connected "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$CREDENTIALS" "$SSLOPTION"; then
-                            get_sections "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$HOSTNAME" "$CREDENTIALS" "$SSLOPTION"
-                        else
-                            get_empty_sections "$SID" "$INSTANCE" "$db_name" "$INSTANCE_USER" "$CREDENTIALS" "$SSLOPTION"
-                        fi
+                    if database_connected "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$CREDENTIALS" "$SSLOPTION"; then
+                        get_sections "$SID" "$INSTANCE" "$INSTANCE_USER" "$db_name" "$HOSTNAME" "$CREDENTIALS" "$SSLOPTION"
+                    else
+                        get_empty_sections "$SID" "$INSTANCE" "$db_name" "$INSTANCE_USER" "$CREDENTIALS" "$SSLOPTION"
                     fi
-                done
+                fi
+            done
 
-            elif [ "$replication_mode" = "logreplay" ] || [ "$replication_mode" = "delta_datashipping" ]; then
-                echo "<<<sap_hana_status:sep(59)>>>"
-                echo "[[${SID} ${INSTANCE}]]"
-                echo "all started;ok;HANA DB is in replication mode \"$replication_mode\" and cannot be connected to"
-
-            else
-                echo "<<<sap_hana_status:sep(59)>>>"
-                echo "[[${SID} ${INSTANCE}]]"
-                echo "all started;unknown;HANA DB is in replication mode \"$replication_mode\""
-            fi
         done
 else
 
@@ -891,45 +872,32 @@ else
             continue
         fi
 
-        replication_mode=$(get_operation_mode "$INSTANCE_USER")
-        if [ -z "$replication_mode" ] || [ "$replication_mode" = "primary" ] || [ "$replication_mode" = "logreplay_readaccess" ]; then
+        SAP_LANDSCAPE=$(su - "${INSTANCE_USER}" -c "python /usr/sap/${SID}/HDB${INSTANCE}/exe/python_support/landscapeHostConfiguration.py")
+        HOSTNAME=$(sap_hana_host_from_landscape "$SAP_LANDSCAPE")
+        SSLOPTION=$(get_ssl_option "$SID" "$HOSTNAME")
 
-            SAP_LANDSCAPE=$(su - "${INSTANCE_USER}" -c "python /usr/sap/${SID}/HDB${INSTANCE}/exe/python_support/landscapeHostConfiguration.py")
-            HOSTNAME=$(sap_hana_host_from_landscape "$SAP_LANDSCAPE")
-            SSLOPTION=$(get_ssl_option "$SID" "$HOSTNAME")
+        CREDENTIALS=$(get_credentials "${USER}" "${PASSWORD}" "${USERSTOREKEY}")
+        INSTANCE_STATUS=$(mk_hdbsql "$SID" "$INSTANCE" "$INSTANCE_USER" "SYSTEMDB" "$(query_sap_hana_db_status)" "$CREDENTIALS" "$SSLOPTION")
+        rc=$?
 
-            CREDENTIALS=$(get_credentials "${USER}" "${PASSWORD}" "${USERSTOREKEY}")
-            INSTANCE_STATUS=$(mk_hdbsql "$SID" "$INSTANCE" "$INSTANCE_USER" "SYSTEMDB" "$(query_sap_hana_db_status)" "$CREDENTIALS" "$SSLOPTION")
-            rc=$?
+        if [ $rc != 0 ]; then
+            INSTANCE_STATUS_ERROR=$INSTANCE_STATUS
+            echo "$INSTANCE_STATUS_ERROR" 1>&2
+        fi
 
-            if [ $rc != 0 ]; then
-                INSTANCE_STATUS_ERROR=$INSTANCE_STATUS
-                echo "$INSTANCE_STATUS_ERROR" 1>&2
-            fi
+        set_sap_hana_version "$INSTANCE_USER"
 
-            set_sap_hana_version "$INSTANCE_USER"
-
-            query_instance "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$SAP_LANDSCAPE" "SYSTEMDB" "$CREDENTIALS" "$SSLOPTION"
-            # We only execute all SQL queries in case the SQL DB is open & responding.
-            # Otherwise only execute sections which are using other interfaces (e.g. python or odbcreg).
-            # This accelerates the plugin execution tremendously as we do not have to wait for all the sql timeouts.
-            if [ -z "$INSTANCE_STATUS_ERROR" ]; then
-                query_databases "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$CREDENTIALS" "$SSLOPTION"
-            else
-                echo "<<<sap_hana_status:sep(59)>>>"
-                echo "[[${SID} ${INSTANCE}]]"
-                echo "$INSTANCE_STATUS_ERROR"
-            fi
-
-        elif [ "$replication_mode" = "logreplay" ]; then
-            echo "<<<sap_hana_status:sep(59)>>>"
-            echo "[[${SID} ${INSTANCE}]]"
-            echo "all started;ok;HANA DB is in replication mode logreplay and cannot be connected to"
-
+        query_instance "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$SAP_LANDSCAPE" "SYSTEMDB" "$CREDENTIALS" "$SSLOPTION"
+        # We only execute all SQL queries in case the SQL DB is open & responding.
+        # Otherwise only execute sections which are using other interfaces (e.g. python or odbcreg).
+        # This accelerates the plugin execution tremendously as we do not have to wait for all the sql timeouts.
+        if [ -z "$INSTANCE_STATUS_ERROR" ]; then
+            query_databases "$SID" "$INSTANCE" "$INSTANCE_USER" "$HOSTNAME" "$CREDENTIALS" "$SSLOPTION"
         else
             echo "<<<sap_hana_status:sep(59)>>>"
             echo "[[${SID} ${INSTANCE}]]"
-            echo "all started;unknown;HANA DB is in replication mode \"$replication_mode\""
+            echo "$INSTANCE_STATUS_ERROR"
         fi
+
     done
 fi
