17591 FIX SAP HANA: unset status error
The instance status error would carry over to subsequent host checks
even if the subsequent host was ok. This change makes it so that the
status error is always handled.

SUP-22146

Co-authored-by: Marcel Schulte <marcel.schulte@checkmk.com>
Co-authored-by: Moritz Kiemer <moritz.kiemer@checkmk.com>
Change-Id: I5d1971b50d2ecf78e7aa8747c5873dad6452c2a8

diff --git a/agents/plugins/mk_sap_hana b/agents/plugins/mk_sap_hana
--- a/agents/plugins/mk_sap_hana
+++ b/agents/plugins/mk_sap_hana
@@ -880,10 +880,15 @@ else
         INSTANCE_STATUS=$(mk_hdbsql "$SID" "$INSTANCE" "$INSTANCE_USER" "SYSTEMDB" "$(query_sap_hana_db_status)" "$CREDENTIALS" "$SSLOPTION")
         rc=$?
 
-        if [ $rc != 0 ]; then
-            INSTANCE_STATUS_ERROR=$INSTANCE_STATUS
-            echo "$INSTANCE_STATUS_ERROR" 1>&2
-        fi
+        case "${rc}" in
+            0)
+                INSTANCE_STATUS_ERROR=""
+                ;;
+            *)
+                INSTANCE_STATUS_ERROR=$INSTANCE_STATUS
+                echo "$INSTANCE_STATUS_ERROR" 1>&2
+                ;;
+        esac
 
         set_sap_hana_version "$INSTANCE_USER"
 
@@ -898,6 +903,5 @@ else
             echo "[[${SID} ${INSTANCE}]]"
             echo "$INSTANCE_STATUS_ERROR"
         fi
-
     done
 fi
